<a href="https://colab.research.google.com/github/goetzdominik/Digichem/blob/main/jonas_digichem_dataset_creation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install --upgrade numpy
!pip install --upgrade mendeleev
!pip install --upgrade pymatgen

Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (1.26.4)
Collecting numpy
  Using cached numpy-2.2.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
Using cached numpy-2.2.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.4 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mendeleev 1.0.0 requires numpy<2.0,>=1.21; python_version < "3.12", but you have numpy 2.2.5 which is incompatible.
tensorflow 2.18.0 requires numpy<2.1.0,>=1.26.0, but you have numpy 2.2.5 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.2.5 which is incompatible.
Successfully installed numpy-2.2.5
Requirement already satisfied: mendeleev in /usr/local/lib/python3.11/dist-packages (1.0.0)
Requirement already satisfied: Pygments<3.0.0,>=2.11.2 in /usr/local/lib/python3.11/dist-packages (from mendeleev) (2.19.1)
Requirement already satisfied: SQLAlchemy>=1.4.0 in /usr/local/lib/python3.11/dist-packages (from mendeleev) (2.0.40)
Requirement already satisfied: colorama<0.5.0,>=0.4.6 in /usr/local/lib/python3.11/dist-packages (from mendeleev) (0.4.6)
Requirement already satisfied: deprecated<2.0.0,>=1.2.14 in /usr/local/lib/python3.11/dist-packages (from mendeleev) (1.2.18)
Collecting numpy<2.0,>=1.21 (from mendeleev)
  Using cached numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from mendeleev) (2.2.2)
Requirement already satisfied: pydantic<3.0.0,>=2.9.2 in /usr/local/lib/python3.11/dist-packages (from mendeleev) (2.11.3)
Requirement already satisfied: pyfiglet<0.9,>=0.8.post1 in /usr/local/lib/python3.11/dist-packages (from mendeleev) (0.8.post1)
Requirement already satisfied: wrapt<2,>=1.10 in /usr/local/lib/python3.11/dist-packages (from deprecated<2.0.0,>=1.2.14->mendeleev) (1.17.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.0->mendeleev) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.0->mendeleev) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.0->mendeleev) (2025.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3.0.0,>=2.9.2->mendeleev) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.1 in /usr/local/lib/python3.11/dist-packages (from pydantic<3.0.0,>=2.9.2->mendeleev) (2.33.1)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.11/dist-packages (from pydantic<3.0.0,>=2.9.2->mendeleev) (4.13.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3.0.0,>=2.9.2->mendeleev) (0.4.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.11/dist-packages (from SQLAlchemy>=1.4.0->mendeleev) (3.2.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->mendeleev) (1.17.0)
Using cached numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.3 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.2.5
    Uninstalling numpy-2.2.5:
      Successfully uninstalled numpy-2.2.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.
Successfully installed numpy-1.26.4
Requirement already satisfied: pymatgen in /usr/local/lib/python3.11/dist-packages (2025.5.2)
Requirement already satisfied: joblib>=1 in /usr/local/lib/python3.11/dist-packages (from pymatgen) (1.4.2)
Requirement already satisfied: matplotlib>=3.8 in /usr/local/lib/python3.11/dist-packages (from pymatgen) (3.10.0)
Requirement already satisfied: monty>=2025.1.9 in /usr/local/lib/python3.11/dist-packages (from pymatgen) (2025.3.3)
Requirement already satisfied: networkx>=2.7 in /usr/local/lib/python3.11/dist-packages (from pymatgen) (3.4.2)
Requirement already satisfied: palettable>=3.3.3 in /usr/local/lib/python3.11/dist-packages (from pymatgen) (3.3.3)
Requirement already satisfied: pandas>=2 in /usr/local/lib/python3.11/dist-packages (from pymatgen) (2.2.2)
Requirement already satisfied: plotly>=5.0.0 in /usr/local/lib/python3.11/dist-packages (from pymatgen) (5.24.1)
Requirement already satisfied: bibtexparser>=1.4.0 in /usr/local/lib/python3.11/dist-packages (from pymatgen) (1.4.3)
Requirement already satisfied: requests>=2.32 in /usr/local/lib/python3.11/dist-packages (from pymatgen) (2.32.3)
Requirement already satisfied: ruamel.yaml>=0.17.0 in /usr/local/lib/python3.11/dist-packages (from pymatgen) (0.18.10)
Requirement already satisfied: scipy>=1.13.0 in /usr/local/lib/python3.11/dist-packages (from pymatgen) (1.15.2)
Requirement already satisfied: spglib>=2.5 in /usr/local/lib/python3.11/dist-packages (from pymatgen) (2.6.0)
Requirement already satisfied: sympy>=1.3 in /usr/local/lib/python3.11/dist-packages (from pymatgen) (1.13.1)
Requirement already satisfied: tabulate>=0.9 in /usr/local/lib/python3.11/dist-packages (from pymatgen) (0.9.0)
Requirement already satisfied: tqdm>=4.60 in /usr/local/lib/python3.11/dist-packages (from pymatgen) (4.67.1)
Requirement already satisfied: uncertainties>=3.1.4 in /usr/local/lib/python3.11/dist-packages (from pymatgen) (3.2.3)
Requirement already satisfied: numpy<3,>=1.25.0 in /usr/local/lib/python3.11/dist-packages (from pymatgen) (1.26.4)
Requirement already satisfied: pyparsing>=2.0.3 in /usr/local/lib/python3.11/dist-packages (from bibtexparser>=1.4.0->pymatgen) (3.2.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.8->pymatgen) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.8->pymatgen) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.8->pymatgen) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.8->pymatgen) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.8->pymatgen) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.8->pymatgen) (11.2.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.8->pymatgen) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=2->pymatgen) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=2->pymatgen) (2025.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.11/dist-packages (from plotly>=5.0.0->pymatgen) (9.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32->pymatgen) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32->pymatgen) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32->pymatgen) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32->pymatgen) (2025.4.26)
Requirement already satisfied: ruamel.yaml.clib>=0.2.7 in /usr/local/lib/python3.11/dist-packages (from ruamel.yaml>=0.17.0->pymatgen) (0.2.12)
Requirement already satisfied: typing-extensions>=4.9.0 in /usr/local/lib/python3.11/dist-packages (from spglib>=2.5->pymatgen) (4.13.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy>=1.3->pymatgen) (1.3.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib>=3.8->pymatgen) (1.17.0)

In [61]:
import pandas as pd
import numpy as np
import pymatgen
from pymatgen.core import Element
from mendeleev import element

import ast

pd.set_option('display.max_rows', 100)  # Display 10 rows
pd.set_option('display.max_columns', None)  # Display all columns

df_ABC3 = pd.read_csv("../ABC3_filtered.csv")
df_A2BCX6 = pd.read_csv("../A2BCX6_filtered.csv")

#Merge the two pervoskites data frames and treat them as one
df = pd.concat([df_ABC3, df_A2BCX6], axis=0,ignore_index=True)
df.to_csv("df.csv", index=False)
print(df)

C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\4113363447.py:12: DtypeWarning: Columns (64,334,436,534,540,570,602,608,614,620,690,696,704,710,716,722,728,772,778,784,790,796,802,808,814,834,846,858,870,896,902,908,914,920,960,966,972,978,992,998,1004,1010,1016,1022,1028,1034,1085,1086,1088,1089,1090,1092,1095,1096,1098,1099,1101,1102,1103,1105,1108,1109,1137,1138,1140,1141,1142,1143,1144,1147,1148,1150,1151,1153,1154,1155,1156,1157,1160,1161,1189,1190,1192,1193,1194,1196,1199,1200,1202,1203,1205,1206,1207,1209,1212,1213,1214,1220,1226,1232,1262,1268,1274,1280,1301,1302,1303,1304,1305,1306,1313,1314,1315,1316,1317,1318,1349,1350,1351,1352,1353,1354,1361,1362,1363,1364,1365,1366,1397,1398,1399,1400,1401,1402,1409,1410,1411,1412,1413,1414,1433,1439,1445,1451,1562,1564,1582,1583,1584,1585,1586,1587,1588,1589,1590,1591,1592,1593,1631,1632,1633,1634,1636,1637,1638,1639,1640,1641,1661,1662,1663,1664,1665,1666,1667,1668,1669,1670,1671,1672,1673,1674,1675,1676,1677,1678,1679,1680,1686,1691,1692,1693,1695,1696,1697,1699,1700,1701,1702,1703,1704,1705,1706,1707,1708,1709,1710,1711,1712,1713,1714,1715,1748,1754,1760,1766,1782,1785,1786,1792,1798,1804,1852,1858,1864,1870,1878,1884,1890,1896,1914,1920,1926,1932,1938,1939,1940,1941,1942,1943,1944,1945,1946,1947,1948,1949,1950,1951,1952,1953,1954,1955,1956,1957,1958,1959,1960,1961,1962,1963,1964,1965,1966,1967,1970,1971,1972,1973,1974,1975,1976,1982,1988,1994,2002,2003,2006,2007,2008,2014,2020,2026,2032,2033,2036,2037,2038,2039,2040,2041,2042,2043,2045,2047,2048,2049,2050,2051,2052,2053,2054,2055,2058,2059,2060,2061,2062,2063,2132,2133,2134,2135,2136,2137,2216,2228,2240,2252,2294,2297,2304,2307,2308,2314,2320,2326,2360,2366,2372,2378,2394,2400,2406,2412,2445,2451,2457,2463,2469,2475,2481,2487,2493,2494,2498,2504,2510,2516,2522,2528,2534,2540,2596,2602,2608,2614,2623,2629,2635,2641,2699,2705,2711,2717,2723,2729,2735,2741,2749,2755,2761,2767,2775,2781,2787,2793,2801,2807,2813,2819,2825,2831,2837,2843,2849,2855,2861,2867,2873,2879,2885,2891,2955,2961,2967,2973,3031,3037,3043,3049,3055,3061,3067,3073,3081,3087,3093,3099,3107,3113,3119,3125,3131,3137,3143,3149,3155,3161,3167,3173,3181,3187,3193,3199,3205,3206,3207,3208,3209,3212,3213,3215,3216,3218,3219,3220,3221,3222,3223,3224,3225,3226,3227,3228,3229,3230,3231,3232,3233,3234,3235,3236,3237,3238,3239,3240,3241,3242,3243,3244,3247,3253,3259,3265,3271,3277,3283,3289,3297,3298,3299,3300,3305,3306,3308,3309,3312,3315,3317,3318,3319,3320,3321,3322,3327,3333,3339,3345,3377,3383,3389,3395,3401,3407,3415,3416,3417,3418,3419,3420,3421,3422,3425,3426,3427,3428,3429,3430,3431,3432,3435,3436,3437,3438,3439,3440,3441,3442,3443,3444,3445,3446,3449,3455,3461,3467,3473,3479,3485,3491,3499,3505,3511,3517,3523,3529,3535,3541,3555,3561,3567,3573,3579,3585,3591,3597,3603,3609,3617,3623,3629,3635,3641,3642,3643,3649,3655,3661,3667,3668,3669,3670,3671,3672,3673,3674,3675,3676,3703,3709,3715,3721,3729,3735,3741,3747,3753,3759,3765,3771,3865,3877,3889,3901,3913,3925,3926,3927,3928,3929,3930,3931,3932,3933,3934,3935,3936,3937,3938,3939,3940,3941,3942,3943,3944,3945,3946,3947,3948,3949,3950,3951,3952,3953,3954,3955,3956,3959,3965,3971,3977,3983,3989,3995,4001,4071,4072,4073,4074,4075,4081,4087,4093,4171,4177,4183,4189,4199,4205,4211,4217,4225,4231,4237,4243,4249,4255,4261,4267,4275,4287,4299,4311,4325,4331,4337,4343,4349,4355,4361,4367,4373,4379,4380,4381,4382,4383,4384,4385,4386,4387,4388,4389,4395,4401,4407,4415,4421,4427,4433,4439,4445,4451,4457,4465,4471,4477,4483,4489,4495,4501,4507,4513,4519,4525,4531,4537,4543,4549,4555,4563,4575,4587,4599,4613,4619,4625,4631,4663,4669,4675,4681,4713,4719,4725,4731,4737,4743,4749,4755,4809,4810,4811,4812,4813,4814,4815,4816,4817,4818,4821,4827,4833,4839,4845,4851,4857,4863,4883,4889,4895,4901,4907,4913,4919,4925,4931,4937,4943,4944,4945,4946,4949,4950,4951,4952,4953,4954,4965,4966,4967,4968,4969,4970,4973,4979,4985,4991,4997,5003,5009,5015,5021,5022,5023,5024,5025,5031,5037,5043,5051,5052,5053,5054,5055,5056,5057,5058,5059,5065,5071,5077,5083,5089,5095,5101,5107,5119,5155,5161,5167,5173,5191,5221,5227,5233,5239,5245,5251,5257,5263,5281,5293,5299,5305,5311,5329,5335,5341,5347,5359,5365,5383,5389,5395,5401,5407,5433,5439,5445,5451,5457,5463,5469,5475,5481,5517,5553,5597,5603,5609,5615,5621,5627,5633,5639,5645,5646,5647,5648,5649,5650,5651,5652,5653,5654,5655,5656,5657,5658,5671,5677,5683,5689,5695,5701,5707,5713,5719,5725,5745,5751,5757,5763,5769,5775,5781,5787,5793,5799,5807,5813,5819,5825,5831,5837,5843,5849,5855,5856,5857,5858,5859,5860,5861,5862,5863,5864,5865,5866,5867,5868,5869,5870,5871,5872,5873,5874,5875,5876,5879,5885,5891,5897,5903,5904,5905,5906,5907,5908,5909,5910,5911,5912,5915,5921,5927,5933,5939,5945,5951,5957,5963,5969,5975,5981,5987,5993,5999,6005,6011,6017,6023,6029,6035,6059,6083,6089,6095,6101,6107,6113,6185,6191,6227,6263,6269,6275,6281,6287,6293,6299,6300,6301,6307,6313,6319,6325,6331,6337,6338,6339,6345,6351,6357,6375,6381,6387,6393,6399,6405,6411,6417,6423,6429,6463,6469,6503,6504,6505,6506,6507,6508,6509,6510,6589,6595,6619) have mixed types. Specify dtype option on import or set low_memory=False.
  df_ABC3 = pd.read_csv("../ABC3_filtered.csv")
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\4113363447.py:13: DtypeWarning: Columns (66,193,194,195,200,201,205,262,270,274,276,277,278,279,283,284,285,288,289,346,354,361,362,363,368,369,373,381,387,393,399,557,558,559,560,562,563,564,565,566,567,568,570,571,572,579,580,581,582,583,584,585,586,587,588,589,591,592,594,595,598,599,600,601,603,604,605,606,608,609,610,611,612,613,614,616,617,618,620,621,622,623,624,626,628,629,630,637,638,639,640,642,644,645,647,649,650,652,656,658,659,661,662,663,664,667,668,671,672,757,763,769,775,783,789,795,801,890,891,905,906,908,909,911,914,915,916,917,920,921,923,926,927,928,929,933,934,936,937,940,941,942,945,946,947,948,949,951,954,981,986,992,994,995,996,998,999,1000,1002,1009,1010,1020,1021,1023,1026,1028,1030,1032,1035,1037,1039,1043,1046,1047,1048,1051,1052,1053,1056,1059,1065,1071,1077,1087,1089,1115,1119,1187,1193,1199,1205,1222,1224,1226,1228,1236,1242,1248,1254,1284,1290,1296,1302,1308,1314,1320,1326,1381,1382,1385,1386,1387,1388,1389,1390,1391,1392,1397,1403,1409,1415,1421,1427,1433,1439,1487,1499,1511,1523,1531,1537,1543,1549,1555,1561,1567,1573,1630,1634,1641,1647,1653,1659,1665,1671,1677,1683,1775,1781,1787,1793,1799,1805,1811,1823,1829,1835,1841,1849,1855,1861,1867,1901,1902,1903,1904,1905,1906,1907,1908,1909,1915,1921,1927,1933,1939,1945,1951,1957,1963,1969,1975,1981,1997,2003,2009,2015,2021,2031,2037,2043,2049,2055,2071,2083,2095,2107,2113,2133,2139,2145,2151,2165,2171,2177,2183,2189,2195,2201,2207,2245,2246,2251,2257,2263,2269,2275,2281,2287,2293,2299,2305,2311,2317,2323,2324,2325,2326,2327,2328,2329,2335,2341,2347,2353,2359,2365,2371,2378,2380,2383,2385,2387,2388,2389,2390,2391,2392,2393,2394,2395,2396,2459,2465,2471,2477,2483,2491,2497,2503,2509,2515,2521,2527,2533,2539,2545,2551,2557,2563,2569,2575,2581,2661,2667,2685,2691,2697,2703,2709,2715,2721,2785,2791,2797,2803,2809,2815,2821,2827,2833,2839,2845,2846,2847,2848,2849,2850,2851,2852,2853,2854,2893,2905,2917,2929,2977,2978,2983,2989,2995,3001,3009,3015,3021,3027,3033,3039,3045,3051,3057,3063,3069,3075,3081,3095,3107,3119,3131,3139,3145,3151,3157,3163,3169,3175,3181,3195,3207,3219,3231,3289,3295,3301,3307,3313,3319,3325,3331,3339,3345,3351,3357,3363,3369,3375,3381,3387,3393,3399,3405,3413,3419,3425,3431,3437,3443,3449,3455,3463,3469,3475,3481,3487,3493,3499,3505,3511,3512,3513,3519,3525,3531,3537,3543,3549,3555,3561,3567,3573,3579,3609,3621,3633,3645,3719,3725,3737,3749,3761,3773,3779,3785,3817,3825,3831,3837,3843,3849,3855,3861,3867,3893,3905,3917,3929,3949,3955,3961,3967,3973,3979,3985,3991,3997,4005,4011,4017,4023,4031,4037,4043,4049,4055,4061,4067,4073,4079,4080,4081,4082,4083,4084,4085,4086,4087,4088,4089,4090,4091,4092,4093,4094,4095,4096,4097,4098,4099,4100,4101,4102,4103,4104,4105,4106,4107,4108,4109,4110,4111,4112,4113,4114,4115,4116,4143,4149,4155,4161,4167,4173,4179,4185,4223,4229,4235,4253,4259,4265,4271,4279,4285,4291,4297,4311,4317,4323,4329,4341,4347,4379,4385,4391,4397,4415,4421,4427,4433,4441,4453,4465,4477,4495,4501,4507,4513,4525,4531,4537,4543,4549,4555,4561,4567,4573,4579,4585,4591,4597,4603,4609,4615,4649,4650,4652,4655,4656,4658,4661,4662,4664,4667,4668,4670,4683,4695,4696,4697,4698,4703,4709,4715,4721,4729,4735,4741,4747,4755,4761,4767,4773,4783,4789,4795,4801,4807,4808,4809,4810,4811,4812,4813,4814,4815,4816,4817,4818,4819,4820,4821,4822,4823,4824,4825,4826,4827,4828,4829,4830,4831,4832,4833,4834,4835,4836,4837,4838,4839,4840,4841,4842,4843,4844,4845,4846,4847,4848,4849,4850,4851,4852,4877,4878,4879,4880,4881,4882,4883,4884,4885,4886,4887,4888,4889,4890,4891,4892,4901,4902,4903,4904,4905,4906,4907,4913,4919,4925,4931,4932,4933,4934,4935,4936,4945,4946,4947,4948,4957,4958,4959,4960,4969,4970,4971,4972,4979,4980,4981,4982,4983,4984,4985,4986,5011,5017,5023,5029,5035,5041,5047,5053,5059,5065,5071,5077,5115,5116,5117,5118,5119,5120,5121,5122,5123,5129,5135,5141,5147,5153,5159,5165,5171,5172,5211,5223,5235,5247,5283,5289,5295,5301,5357,5363,5369,5375,5381,5387,5393,5399,5405,5411,5417,5423,5477,5483,5489,5501,5507,5575,5581,5587,5593,5599,5605,5611,5617,5623,5629,5635,5641,5659,5660,5661,5662,5663,5664,5665,5666,5667,5668,5669,5670,5671,5672,5673,5674,5677,5683,5689,5695,5701,5707,5713,5719,5749,5755,5779,5785,5786,5787,5788,5789,5790,5791,5792,5793,5799,5805,5811,5817,5823,5893,5899,5905,5911,5917,5953,5954,6113,6119,6125,6131,6143,6144,6145,6146,6147,6148,6149,6150,6151,6169,6170,6183,6189,6195,6201,6207,6221,6222,6223,6224,6225,6226) have mixed types. Specify dtype option on import or set low_memory=False.
  df_A2BCX6 = pd.read_csv("../A2BCX6_filtered.csv")
IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

In [62]:
#test mendeleev package
Fe = element("Fe")

print(Fe.fusion_heat)
print(Fe.evaporation_heat)
print(Fe.specific_heat)
print(Fe.electrons)

13.8
340.0
0.449
26

In [63]:
#test pymatgen package
element = Element("Fe")  # Iron

print(element.Z)
print(element.group)
print(element.row)
print(element.mendeleev_no)
print(element.iupac_ordering)
print(element.average_ionic_radius)
print(element.atomic_radius)
print(element.atomic_radius_calculated)
print(element.van_der_waals_radius)
print(element.X)
print(element.electron_affinity)
print(element.ionization_energy)
print(element.valence[1])
print(element.atomic_mass)
print(element.density_of_solid)
print(element.molar_volume)
print(element.boiling_point)
print(element.melting_point)
print(element.thermal_conductivity)

26
8
4
61.0
64
0.8525 ang
1.4 ang
1.56 ang
2.04 ang
1.83
0.15323635
7.9024681
6
55.845 amu
7874.0 kg m^-3
7.09 cm^3
3134.0 K
1811.0 K
80.0 W K^-1 m^-1

In [64]:
#add the missing values to the mendeleev functions of fusion heat, evaporation heat and specific heat (and BP)
missing_fusion_heats = {
    "As": 24.44,  # kJ/mol
    "O" : 0.44,
    "N" : 0.72,
    "C" : 117,
    "Ru" : 38.59,
    "Tb" : 10.15,
    "Gd" : 10.05,
    "Dy" : 11.06,
    "Eu" : 9.21,
    "Ho" : 17.0,
    "Er" : 19.9,
    "Lu" : 22,
    "Tm" : 16.84
}

from mendeleev import element

def get_fusion_heat(element_symbol):
    elmt = element(element_symbol)
    if elmt.fusion_heat is None and element_symbol in missing_fusion_heats:
        return missing_fusion_heats[element_symbol]
    elif elmt.fusion_heat is None and element_symbol not in missing_fusion_heats:
        print(elmt.name, "is missing fusion heat value")
    else:
        return elmt.fusion_heat

missing_evaporation_heats = {
    "O" : 6.82, # kJ/mol
    "N" : 5.58,
    "C" : 715,
    "Ru" : 619,
    "Tb" : 391
}

from mendeleev import element

def get_evaporation_heat(element_symbol):
    elmt = element(element_symbol)
    if elmt.evaporation_heat is None and element_symbol in missing_evaporation_heats:
        return missing_evaporation_heats[element_symbol]
    else:
        return elmt.evaporation_heat

missing_specific_heats = {
    "Pa" : 99.1,
    "Tc" : 63
}

def get_specific_heat(element_symbol):
    elmt = element(element_symbol)
    if elmt.specific_heat is None and element_symbol in missing_specific_heats:
        return missing_specific_heats[element_symbol]
    else:
        return elmt.specific_heat

def get_boiling_point(element_symbol):
    elmt = element(element_symbol)
    if element_symbol == "Pa":
        return 4000
    elif element_symbol == "P":
        return 550
    else:
        return elmt.boiling_point

In [6]:
#define function to handle missing values (use atomic radius instead of calculated and use atomic mass/molar volume instead of density of solid)
def get_atomic_radius_calculated(elmt_pymatgen_temp):
    atomic_radius_calculated_temp = elmt_pymatgen_temp.atomic_radius_calculated
    if atomic_radius_calculated_temp == None:
        return elmt_pymatgen_temp.atomic_radius
    else :
      return atomic_radius_calculated_temp

def get_density_of_solid(elmt_pymatgen_temp):
    density_of_solid_temp = elmt_pymatgen_temp.density_of_solid
    if density_of_solid_temp == None:
        return elmt_pymatgen_temp.atomic_mass / elmt_pymatgen_temp.molar_volume *1000
    else :
      return density_of_solid_temp

In [65]:
#create dictionary with the values for all elements (so that the loop over all formulas is faster) (takes approx 4 minutes now)

#find all elements in the csv file to create input for dictionary creation
elements_list = pd.read_csv('df.csv', usecols= ['elements'])
elements_vector = []
for index in elements_list.index: # Iterate over DataFrame index to get row
  formula = elements_list.loc[index, 'elements'] # Access element string using loc
  formula = ast.literal_eval(formula) # Safely evaluate string as list
  for elmt in formula:
    elements_vector.append(elmt)

elements_vector = pd.Series(elements_vector).drop_duplicates().tolist() # Deduplicate elements


#loop over the found unique elements and define the needed properties
elemental_properties = {}  #dictionary to be filled

for symbol in elements_vector:
    #define strings as "elements"
    elmt_pymatgen = Element(symbol)
    elmt_mendeleev = element(symbol)

    properties = {
        'atomic_mass': elmt_pymatgen.atomic_mass,
        'Z': elmt_pymatgen.Z,
        'group': elmt_pymatgen.group,
        'fusion_heat': get_fusion_heat(symbol),  # Use custom function
        'evaporation_heat': get_evaporation_heat(symbol),  # Use custom function
        'specific_heat': get_specific_heat(symbol), # Use custom function
        'row': elmt_pymatgen.row,
        'mendeleev_no': elmt_pymatgen.mendeleev_no,
        'iupac_ordering': elmt_pymatgen.iupac_ordering,
        'average_ionic_radius': elmt_pymatgen.average_ionic_radius,
        'atomic_radius': elmt_pymatgen.atomic_radius,
        'atomic_radius_calculated': get_atomic_radius_calculated(elmt_pymatgen), # Use custom function
        'van_der_waals_radius': elmt_pymatgen.van_der_waals_radius,
        'X': elmt_pymatgen.X,
        'electron_affinity': elmt_pymatgen.electron_affinity,
        'ionization_energy': elmt_pymatgen.ionization_energy,
    #    'valence': elmt_pymatgen.valence[1],
        'density_of_solid': get_density_of_solid(elmt_pymatgen), # Use custom function
        'molar_volume': elmt_pymatgen.molar_volume,
        'boiling_point': get_boiling_point(symbol), # Use custom function
        'melting_point': elmt_pymatgen.melting_point,
        'thermal_conductivity': elmt_pymatgen.thermal_conductivity

    }

    elemental_properties[symbol] = properties  # For dictionary

C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2885943200.py:10: UserWarning: No data available for density_of_solid for Br
  density_of_solid_temp = elmt_pymatgen_temp.density_of_solid
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2885943200.py:10: UserWarning: No data available for density_of_solid for O
  density_of_solid_temp = elmt_pymatgen_temp.density_of_solid
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2885943200.py:10: UserWarning: No data available for density_of_solid for Cl
  density_of_solid_temp = elmt_pymatgen_temp.density_of_solid
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2885943200.py:10: UserWarning: No data available for density_of_solid for N
  density_of_solid_temp = elmt_pymatgen_temp.density_of_solid
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2885943200.py:10: UserWarning: No data available for density_of_solid for F
  density_of_solid_temp = elmt_pymatgen_temp.density_of_solid
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2885943200.py:3: UserWarning: No data available for atomic_radius_calculated for Ce
  atomic_radius_calculated_temp = elmt_pymatgen_temp.atomic_radius_calculated
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2885943200.py:10: UserWarning: No data available for density_of_solid for H
  density_of_solid_temp = elmt_pymatgen_temp.density_of_solid
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2885943200.py:3: UserWarning: No data available for atomic_radius_calculated for Th
  atomic_radius_calculated_temp = elmt_pymatgen_temp.atomic_radius_calculated
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2885943200.py:10: UserWarning: No data available for density_of_solid for Hg
  density_of_solid_temp = elmt_pymatgen_temp.density_of_solid
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2885943200.py:3: UserWarning: No data available for atomic_radius_calculated for Ho
  atomic_radius_calculated_temp = elmt_pymatgen_temp.atomic_radius_calculated
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2885943200.py:3: UserWarning: No data available for atomic_radius_calculated for U
  atomic_radius_calculated_temp = elmt_pymatgen_temp.atomic_radius_calculated
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2885943200.py:3: UserWarning: No data available for atomic_radius_calculated for La
  atomic_radius_calculated_temp = elmt_pymatgen_temp.atomic_radius_calculated
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2885943200.py:3: UserWarning: No data available for atomic_radius_calculated for Pa
  atomic_radius_calculated_temp = elmt_pymatgen_temp.atomic_radius_calculated

In [66]:
#get only relevant columns from materials project file
df = pd.read_csv('df.csv', usecols= ['formula_pretty','elements', 'band_gap','energy_above_hull','formation_energy_per_atom','density','structure.sites'])

#loop over all entries and extract the corresponding elements
index = -1
for formula in df["elements"]:
  index += 1
  #reformat to list
  elements = ast.literal_eval(formula)

  #calculate property and mean/sd
  atomic_mass = []
  Z = []
  group = []
  row = []
  mendeleev_no = []
  iupac_ordering = []
  average_ionic_radius = []
  atomic_radius = []
  atomic_radius_calculated = []
  van_der_waals_radius = []
  X = []
  electron_affinity = []
  ionization_energy = []
  valence = []
  atomic_mass = []
  density_of_solid = []
  molar_volume = []
  fusion_heat = []
  evaporation_heat = []
  specific_heat = []

#use the library to assign the properties
  for elmt in elements:

    atomic_mass.append(elemental_properties[elmt]['atomic_mass'])
    Z.append(elemental_properties[elmt]['Z'])
    group.append(elemental_properties[elmt]['group'])
    row.append(elemental_properties[elmt]['row'])
    mendeleev_no.append(elemental_properties[elmt]['mendeleev_no'])
    iupac_ordering.append(elemental_properties[elmt]['iupac_ordering'])
    average_ionic_radius.append(elemental_properties[elmt]['average_ionic_radius'])
    atomic_radius.append(elemental_properties[elmt]['atomic_radius'])
    atomic_radius_calculated.append(elemental_properties[elmt]['atomic_radius_calculated'])
    van_der_waals_radius.append(elemental_properties[elmt]['van_der_waals_radius'])
    X.append(elemental_properties[elmt]['X'])
    electron_affinity.append(elemental_properties[elmt]['electron_affinity'])
    ionization_energy.append(elemental_properties[elmt]['ionization_energy'])
    #valence.append(elmt.valence[1])
    density_of_solid.append(elemental_properties[elmt]['density_of_solid'])
    molar_volume.append(elemental_properties[elmt]['molar_volume'])
    fusion_heat.append(elemental_properties[elmt]['fusion_heat'])
    evaporation_heat.append(elemental_properties[elmt]['evaporation_heat'])
    specific_heat.append(elemental_properties[elmt]['specific_heat'])

  mean_atomic_mass = np.mean(atomic_mass)
  std_atomic_mass = np.std(atomic_mass)
  mean_Z = np.mean(Z)
  std_Z = np.std(Z)
  mean_group = np.mean(group)
  std_group = np.std(group)
  mean_row = np.mean(row)
  std_row = np.std(row)
  mean_mendeleev_no = np.mean(mendeleev_no)
  std_mendeleev_no = np.std(mendeleev_no)
  mean_iupac_ordering = np.mean(iupac_ordering)
  std_iupac_ordering = np.std(iupac_ordering)
  mean_average_ionic_radius = np.mean(average_ionic_radius)
  std_average_ionic_radius = np.std(average_ionic_radius)
  mean_atomic_radius = np.mean(atomic_radius)
  std_atomic_radius = np.std(atomic_radius)
  mean_atomic_radius_calculated = np.mean(atomic_radius_calculated)
  std_atomic_radius_calculated = np.std(atomic_radius_calculated)
  mean_van_der_waals_radius = np.mean(van_der_waals_radius)
  std_van_der_waals_radius = np.std(van_der_waals_radius)
  mean_X = np.mean(X)
  std_X = np.std(X)
  mean_electron_affinity = np.mean(electron_affinity)
  std_electron_affinity = np.std(electron_affinity)
  mean_ionization_energy = np.mean(ionization_energy)
  std_ionization_energy = np.std(ionization_energy)
  #mean_valence = np.mean(valence)   ##valence not working yet because of ambiguity
  #std_valence = np.std(valence)
  mean_density_of_solid = np.mean(density_of_solid)
  std_density_of_solid = np.std(density_of_solid)
  mean_molar_volume = np.mean(molar_volume)
  std_molar_volume = np.std(molar_volume)
  mean_fusion_heat = np.mean(fusion_heat)
  std_fusion_heat = np.std(fusion_heat)
  mean_evaporation_heat = np.mean(evaporation_heat)
  std_evaporation_heat = np.std(evaporation_heat)
  mean_specific_heat = np.mean(specific_heat)
  std_specific_heat = np.std(specific_heat)

  #add to dataframe
  df.at[index, 'atom_mass_mean'] = mean_atomic_mass
  df.at[index, 'atom_mass_std'] = std_atomic_mass
  df.at[index, 'Z_mean'] = mean_Z
  df.at[index, 'Z_std'] = std_Z
  df.at[index, 'group_mean'] = mean_group
  df.at[index, 'group_std'] = std_group
  df.at[index, 'row_mean'] = mean_row
  df.at[index, 'row_std'] = std_row
  df.at[index, 'mendeleev_no_mean'] = mean_mendeleev_no
  df.at[index, 'mendeleev_no_std'] = std_mendeleev_no
  df.at[index, 'iupac_ordering_mean'] = mean_iupac_ordering
  df.at[index, 'iupac_ordering_std'] = std_iupac_ordering
  df.at[index, 'average_ionic_radius_mean'] = mean_average_ionic_radius
  df.at[index, 'average_ionic_radius_std'] = std_average_ionic_radius
  df.at[index, 'atomic_radius_mean'] = mean_atomic_radius
  df.at[index, 'atomic_radius_std'] = std_atomic_radius
  df.at[index, 'atomic_radius_calculated_mean'] = mean_atomic_radius_calculated
  df.at[index, 'atomic_radius_calculated_std'] = std_atomic_radius_calculated
  df.at[index, 'van_der_waals_radius_mean'] = mean_van_der_waals_radius
  df.at[index, 'van_der_waals_radius_std'] = std_van_der_waals_radius
  df.at[index, 'X_mean'] = mean_X
  df.at[index, 'X_std'] = std_X
  df.at[index, 'electron_affinity_mean'] = mean_electron_affinity
  df.at[index, 'electron_affinity_std'] = std_electron_affinity
  df.at[index, 'ionization_energy_mean'] = mean_ionization_energy
  df.at[index, 'ionization_energy_std'] = std_ionization_energy
  #df.at[index, 'valence_mean'] = mean_valence
  #df.at[index, 'valence_std'] = std_valence
  df.at[index, 'density_of_solid_mean'] = mean_density_of_solid
  df.at[index, 'density_of_solid_std'] = std_density_of_solid
  df.at[index, 'molar_volume_mean'] = mean_molar_volume
  df.at[index, 'molar_volume_std'] = std_molar_volume
  df.at[index, 'fusion_heat_mean'] = mean_fusion_heat
  df.at[index, 'fusion_heat_std'] = std_fusion_heat
  df.at[index, 'evaporation_heat_mean'] = mean_evaporation_heat
  df.at[index, 'evaporation_heat_std'] = std_evaporation_heat
  df.at[index, 'specific_heat_mean'] = mean_specific_heat
  df.at[index, 'specific_heat_std'] = std_specific_heat
# Display the updated dataframe
#df

In [67]:
def get_data (df):
    df_curated = pd.DataFrame()
    df_curated["elements"] = df["elements"]
    df_curated["formula_pretty"] = df["formula_pretty"]
    df_curated["density"] = df["density"]
    df_curated["formation_energy_per_atom"] = df["formation_energy_per_atom"]
    df_curated["energy_above_hull"] = df["energy_above_hull"]
    df_curated["band_gap"] = df["band_gap"]
    df_curated["structure_string"] = df["structure.sites"]
    df_curated["structure_string_split"] = None
    df_curated["atom_mass_mean"] = df["atom_mass_mean"]
    df_curated["atom_mass_std"] = df["atom_mass_std"]
    df_curated["Z_mean"] = df["Z_mean"]
    df_curated["Z_std"] = df["Z_std"]
    df_curated["group_mean"] = df["group_mean"]
    df_curated["group_std"] = df["group_std"]
    df_curated["row_mean"] = df["row_mean"]
    df_curated["row_std"] = df["row_std"]
    df_curated["mendeleev_no_mean"] = df["mendeleev_no_mean"]
    df_curated["mendeleev_no_std"] = df["mendeleev_no_std"]
    df_curated["iupac_ordering_mean"] = df["iupac_ordering_mean"]
    df_curated["iupac_ordering_std"] = df["iupac_ordering_std"]
    df_curated["average_ionic_radius_mean"] = df["average_ionic_radius_mean"]
    df_curated["average_ionic_radius_std"] = df["average_ionic_radius_std"]
    df_curated["atomic_radius_mean"] = df["atomic_radius_mean"]
    df_curated["atomic_radius_std"] = df["atomic_radius_std"]
    df_curated["atomic_radius_calculated_mean"] = df["atomic_radius_calculated_mean"]
    df_curated["atomic_radius_calculated_std"] = df["atomic_radius_calculated_std"]
    df_curated["van_der_waals_radius_mean"] = df["van_der_waals_radius_mean"]
    df_curated["van_der_waals_radius_std"] = df["van_der_waals_radius_std"]
    df_curated["X_mean"] = df["X_mean"]
    df_curated["X_std"] = df["X_std"]
    df_curated["electron_affinity_mean"] = df["electron_affinity_mean"]
    df_curated["electron_affinity_std"] = df["electron_affinity_std"]
    df_curated["ionization_energy_mean"] = df["ionization_energy_mean"]
    df_curated["ionization_energy_std"] = df["ionization_energy_std"]
    df_curated["density_of_solid_mean"] = df["density_of_solid_mean"]
    df_curated["density_of_solid_std"] = df["density_of_solid_std"]
    df_curated["molar_volume_mean"] = df["molar_volume_mean"]
    df_curated["molar_volume_std"] = df["molar_volume_std"]
    df_curated["fusion_heat_mean"] = df["fusion_heat_mean"]
    df_curated["fusion_heat_std"] = df["fusion_heat_std"]
    df_curated["evaporation_heat_mean"] = df["evaporation_heat_mean"]
    df_curated["evaporation_heat_std"] = df["evaporation_heat_std"]
    df_curated["specific_heat_mean"] = df["specific_heat_mean"]
    df_curated["specific_heat_std"] = df["specific_heat_std"]

    for i in range(df_curated.shape[0]):


        df_curated["structure_string_split"].iloc[i] = df_curated["structure_string"].iloc[i].split()
        # #cleans the structure string and removes all the unnecessary characters
        for j in range(len(df_curated["structure_string_split"].iloc[i])):


            df_curated["structure_string_split"].iloc[i][j] = df_curated["structure_string_split"].iloc[i][j].replace("{","")
            df_curated["structure_string_split"].iloc[i][j] = df_curated["structure_string_split"].iloc[i][j].replace("}","")
            df_curated["structure_string_split"].iloc[i][j] = df_curated["structure_string_split"].iloc[i][j].replace("[","")
            df_curated["structure_string_split"].iloc[i][j] = df_curated["structure_string_split"].iloc[i][j].replace("]","")
            df_curated["structure_string_split"].iloc[i][j] = df_curated["structure_string_split"].iloc[i][j].replace(":","")
            df_curated["structure_string_split"].iloc[i][j] = df_curated["structure_string_split"].iloc[i][j].replace("'","")
            df_curated["structure_string_split"].iloc[i][j] = df_curated["structure_string_split"].iloc[i][j].replace(",","")

        df_curated["elements"].iloc[i] = df_curated["elements"].iloc[i].split(",")
        for k in range(len(df_curated["elements"].iloc[i])):
            df_curated["elements"].iloc[i][k] = df_curated["elements"].iloc[i][k].replace("'", "")
            df_curated["elements"].iloc[i][k] = df_curated["elements"].iloc[i][k].replace("[", "")
            df_curated["elements"].iloc[i][k] = df_curated["elements"].iloc[i][k].replace("]", "")
            df_curated["elements"].iloc[i][k] = df_curated["elements"].iloc[i][k].replace(" ", "")


        # df_curated["Elements"].iloc[i] = df_curated["Elements"].iloc[i].split(",")
        # df_curated["Elements"].iloc[i] = df_curated["Elements"].iloc[i].strip("'")
    return df_curated



df_curated = get_data(df)
df_curated

C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2930353774.py:51: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_curated["structure_string_split"].iloc[i] = df_curated["structure_string"].iloc[i].split()
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2930353774.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_curated["structure_string_split"].iloc[i] = df_curated["structure_string"].iloc[i].split()
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2930353774.py:64: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_curated["elements"].iloc[i] = df_curated["elements"].iloc[i].split(",")
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2930353774.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_curated["elements"].iloc[i] = df_curated["elements"].iloc[i].split(",")
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2930353774.py:51: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_curated["structure_string_split"].iloc[i] = df_curated["structure_string"].iloc[i].split()
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2930353774.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_curated["structure_string_split"].iloc[i] = df_curated["structure_string"].iloc[i].split()
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2930353774.py:64: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_curated["elements"].iloc[i] = df_curated["elements"].iloc[i].split(",")
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2930353774.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_curated["elements"].iloc[i] = df_curated["elements"].iloc[i].split(",")
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2930353774.py:51: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_curated["structure_string_split"].iloc[i] = df_curated["structure_string"].iloc[i].split()
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2930353774.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_curated["structure_string_split"].iloc[i] = df_curated["structure_string"].iloc[i].split()
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2930353774.py:64: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_curated["elements"].iloc[i] = df_curated["elements"].iloc[i].split(",")
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2930353774.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_curated["elements"].iloc[i] = df_curated["elements"].iloc[i].split(",")
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2930353774.py:51: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_curated["structure_string_split"].iloc[i] = df_curated["structure_string"].iloc[i].split()
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2930353774.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_curated["structure_string_split"].iloc[i] = df_curated["structure_string"].iloc[i].split()
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2930353774.py:64: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_curated["elements"].iloc[i] = df_curated["elements"].iloc[i].split(",")
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2930353774.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_curated["elements"].iloc[i] = df_curated["elements"].iloc[i].split(",")
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2930353774.py:51: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_curated["structure_string_split"].iloc[i] = df_curated["structure_string"].iloc[i].split()
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2930353774.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_curated["structure_string_split"].iloc[i] = df_curated["structure_string"].iloc[i].split()
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2930353774.py:64: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_curated["elements"].iloc[i] = df_curated["elements"].iloc[i].split(",")
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2930353774.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_curated["elements"].iloc[i] = df_curated["elements"].iloc[i].split(",")
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2930353774.py:51: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_curated["structure_string_split"].iloc[i] = df_curated["structure_string"].iloc[i].split()
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2930353774.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_curated["structure_string_split"].iloc[i] = df_curated["structure_string"].iloc[i].split()
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2930353774.py:64: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_curated["elements"].iloc[i] = df_curated["elements"].iloc[i].split(",")
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2930353774.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_curated["elements"].iloc[i] = df_curated["elements"].iloc[i].split(",")
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2930353774.py:51: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_curated["structure_string_split"].iloc[i] = df_curated["structure_string"].iloc[i].split()
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2930353774.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_curated["structure_string_split"].iloc[i] = df_curated["structure_string"].iloc[i].split()
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2930353774.py:64: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_curated["elements"].iloc[i] = df_curated["elements"].iloc[i].split(",")
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2930353774.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_curated["elements"].iloc[i] = df_curated["elements"].iloc[i].split(",")
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2930353774.py:51: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_curated["structure_string_split"].iloc[i] = df_curated["structure_string"].iloc[i].split()
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\2930353774.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame


,elements,formula_pretty,density,formation_energy_per_atom,energy_above_hull,band_gap,structure_string,structure_string_split,atom_mass_mean,atom_mass_std,Z_mean,Z_std,group_mean,group_std,row_mean,row_std,mendeleev_no_mean,mendeleev_no_std,iupac_ordering_mean,iupac_ordering_std,average_ionic_radius_mean,average_ionic_radius_std,atomic_radius_mean,atomic_radius_std,atomic_radius_calculated_mean,atomic_radius_calculated_std,van_der_waals_radius_mean,van_der_waals_radius_std,X_mean,X_std,electron_affinity_mean,electron_affinity_std,ionization_energy_mean,ionization_energy_std,density_of_solid_mean,density_of_solid_std,molar_volume_mean,molar_volume_std,fusion_heat_mean,fusion_heat_std,evaporation_heat_mean,evaporation_heat_std,specific_heat_mean,specific_heat_std
0,"[Ag, Br, S]",Ag3SBr,5.967646,-0.305716,0.098312,0.2964,"[{'species': [{'element': 'Ag', 'occu': 1}], '...","[species, element, Ag, occu, 1, abc, 0.552885,...",73.279067,31.299080,32.666667,12.762793,14.666667,2.624669,4.000000,0.816497,87.666667,11.897712,89.333333,12.364825,0.949722,0.096840,1.250000,0.254951,1.156667,0.349698,1.920000,0.135892,2.490000,0.425284,2.248389,0.849311,9.916685,1.758155,5496.545332,3631.543621,15.193333,3.889733,7.916667,4.761634,98.053333,110.615679,0.472333,0.193105
1,"[Ag, I, S]",Ag3SI,6.576090,-0.260466,0.066818,0.5478,"[{'species': [{'element': 'Ag', 'occu': 1}], '...","[species, element, Ag, occu, 1, abc, 0.5259809...",88.945890,40.964795,38.666667,16.213849,14.666667,2.624669,4.333333,0.942809,87.333333,11.614168,89.000000,12.083046,1.080000,0.160647,1.333333,0.249444,1.226667,0.318991,1.963333,0.127105,2.390000,0.326905,2.146875,0.717999,9.462501,1.334313,5796.666667,3534.650698,17.173333,6.413581,9.566667,6.072409,102.183333,108.185892,0.385667,0.228085
2,"[Ag, I, S]",Ag3SI,6.373934,-0.210889,0.116396,0.6243,"[{'species': [{'element': 'Ag', 'occu': 1}], '...","[species, element, Ag, occu, 1, abc, 0.5, 0.5,...",88.945890,40.964795,38.666667,16.213849,14.666667,2.624669,4.333333,0.942809,87.333333,11.614168,89.000000,12.083046,1.080000,0.160647,1.333333,0.249444,1.226667,0.318991,1.963333,0.127105,2.390000,0.326905,2.146875,0.717999,9.462501,1.334313,5796.666667,3534.650698,17.173333,6.413581,9.566667,6.072409,102.183333,108.185892,0.385667,0.228085
3,"[Ag, As, O]",AgAsO3,5.320520,-1.243946,0.025765,0.5930,"[{'species': [{'element': 'Ag', 'occu': 1}], '...","[species, element, Ag, occu, 1, abc, 0.546128,...",66.263067,38.001726,29.333333,16.131405,14.000000,2.160247,3.666667,1.247219,87.000000,12.328828,86.000000,10.424331,1.002222,0.252122,1.116667,0.408928,1.090000,0.478957,1.826667,0.241431,2.516667,0.660824,1.190024,0.280016,10.327613,2.495842,5712.874808,3906.285741,13.526667,2.923062,12.276667,9.800681,97.773333,111.031840,0.494000,0.302259
4,"[Ag, Cl, O]",AgClO3,4.138469,-0.407245,0.038285,2.3983,"[{'species': [{'element': 'Ag', 'occu': 1}], '...","[species, element, Ag, occu, 1, abc, 0.297407,...",53.106867,39.528162,24.000000,16.673332,14.666667,2.624669,3.333333,1.247219,90.333333,13.695092,90.000000,12.832251,1.042222,0.198463,1.066667,0.410961,0.973333,0.494930,1.793333,0.242808,2.843333,0.655862,2.126104,1.053143,11.387307,2.707886,4483.441609,4271.691505,15.006667,3.349352,6.266667,4.700031,93.776667,113.501396,0.544000,0.282596
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1419,"[F, Mo, Na, Rb]",Rb2NaMoF6,3.901772,-2.980085,0.000000,4.1434,"[{'species': [{'element': 'Rb', 'occu': 1}], '...","[species, element, Rb, occu, 1, abc, 0.75, 0.7...",55.848993,35.079400,24.750000,14.872374,6.250000,6.533567,3.750000,1.299038,44.500000,38.147739,44.250000,38.680583,1.075000,0.379589,1.525000,0.673146,1.717500,0.809271,2.235000,0.552879,1.972500,1.272819,1.295568,1.219509,8.457864,5.281427,3619.071500,3855.162776,25.030000,18.588214,8.337500,11.379961,192.560000,231.924237,0.666500,0.388858
1420,"[F, Na, Rb, Rh]",Rb2NaRhF6,4.194014,-2.638313,0.000000,1.9570,"[{'species': [{'element': 'Rb', 'occu': 1}], '...","[species, element, Rb, occu, 1, abc, 0.75, 0.7...",57.590368,37.138772,25.500000,15.771810,7.000000,6.633250,3.750000,1.299038,46.750000,39.015221,46.500000,39.607449,1.067500,0.385689,1.500000,0.677311,1.675000,0.803010,2.217500,0.555760,2.002500,1.278287,1.394481,1.186626,8.549481,5.260082,4161.571500,4792.943375,24.755000,18.824348,6.787500,8.703865,168.560000,190.891937,0.664500,0.391004
1421,"[Cl, Na, Rb, Tm]",Rb2NaTmCl6,3.103076,-2.466064,0.000000,5.0572,"[{'species': [{'element': 'Rb', 'occu': 1}], '...","[species, element, Rb, occu, 1, abc, 0.75, 0.7...",78.211195,57.360685,33.500000,22.643984,5.500000,6.689544,4.250000,1.299038,35.000000,37.229021,38.500000,37.619809,1.173750,0.315384,1.725000,0.480234,1.890000,0.688586,2.330000,0.456508,1.540000,0.948552,1.418947,1.283917,7.117037,3.451624,3464.925101,3402.152426,29.007500,15.621683,7.022500,5.899603,106.527500,77.746680,0.557500,0.403599
1422,"[F, Na, Rb, Y]",Rb2NaYF6,3.583406,-3.568947,0.000000,6.4476,"[{'species': [{'element': 'Rb', 'occu': 1}], '...","[species, element, Rb, occu, 1, abc, 0.25, 0.2...",54.090456,33.148734,24.000000,14.035669,5.500000,6.689544,3.750000,1.299038,36.750000,38.173125,42.000000,38.131352,1.141250,0.342790,1.612500,0.680418,1.772500,0.827084,2.272500,0.552285,1.737500,1.302927,1.186581,1.281545,8.239071,5.351129,2167.071500,1357.886469,27.655000,16.853222,4.212500,4.281912,136.810000,137.107546,0.678250,0.376643
1423,"[Ag, N, O, Rb]",RbAg(NO3)2,3.319109,-1.056313,0.000000,2.5282,"[{'species': [{'element': 'Rb', 'occu': 1}], '...","[species, element, Rb, occu, 1, abc, 0.9528249...",55.835525,41.599394,24.750000,17.612141,10.750000,5.931905,3.500000,1.500000,70.250000,37.358901,67.000000,35.291642,1.159167,0.369552,1.300000,0.725431,1.335000,0.888834,2.052500,0.611325,2.307500,1.021552,0.795376,0.621898,9.976387,4.284475,3494.523167,4045.363750,24.232500,18.374544,3.827500,4.736968,85.575000,101.362932,0.639000,0.345700

In [68]:
def split_df (df):

    # each element has 18 entries in this split
    df["positions"] = None
    for i in range(len(df["structure_string_split"])):
        position_i = []
        for j in range (0, len(df["structure_string_split"].iloc[i]), 18):
            element = df["structure_string_split"].iloc[i][j+2] # remove trailing comma
            x = float(df["structure_string_split"].iloc[i][j+15])
            y = float(df["structure_string_split"].iloc[i][j+16])
            z = float(df["structure_string_split"].iloc[i][j+17])
            position_i.append((element, [x, y, z]))
        df["positions"].iloc[i] = position_i
    return df


df_curated = split_df(df_curated)
df_curated.drop(columns=["structure_string", "structure_string_split"], inplace=True)
df_curated

C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\1626241687.py:13: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["positions"].iloc[i] = position_i
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\1626241687.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["positions"].iloc[i] = position_i
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\1626241687.py:13: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["positions"].iloc[i] = position_i
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\1626241687.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["positions"].iloc[i] = position_i
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\1626241687.py:13: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["positions"].iloc[i] = position_i
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\1626241687.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["positions"].iloc[i] = position_i
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\1626241687.py:13: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["positions"].iloc[i] = position_i
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\1626241687.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["positions"].iloc[i] = position_i
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\1626241687.py:13: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["positions"].iloc[i] = position_i
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\1626241687.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["positions"].iloc[i] = position_i
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\1626241687.py:13: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["positions"].iloc[i] = position_i
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\1626241687.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["positions"].iloc[i] = position_i
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\1626241687.py:13: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["positions"].iloc[i] = position_i
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\1626241687.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["positions"].iloc[i] = position_i
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\1626241687.py:13: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["positions"].iloc[i] = position_i
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\1626241687.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["positions"].iloc[i] = position_i
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\1626241687.py:13: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["positions"].iloc[i] = position_i
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\1626241687.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["positions"].iloc[i] = position_i
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\1626241687.py:13: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["positions"].iloc[i] = position_i
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\1626241687.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["positions"].iloc[i] = position_i
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\1626241687.py:13: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["positions"].iloc[i] = position_i
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\1626241687.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["positions"].iloc[i] = position_i
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\1626241687.py:13: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["positions"].iloc[i] = position_i
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\1626241687.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["positions"].iloc[i] = position_i
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\1626241687.py:13: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["positions"].iloc[i] = position_i
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\1626241687.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["positions"].iloc[i] = position_i
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\1626241687.py:13: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["positions"].iloc[i] = position_i
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\1626241687.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["positions"].iloc[i] = position_i
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\1626241687.py:13: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["positions"].iloc[i] = position_i
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\1626241687.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["positions"].iloc[i] = position_i
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\1626241687.py:13: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["positions"].iloc[i] = position_i
C:\Users\moorh\AppData\Local\Temp\ipykernel_38140\1626241687.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["positions"].iloc[i] = position_i

,elements,formula_pretty,density,formation_energy_per_atom,energy_above_hull,band_gap,atom_mass_mean,atom_mass_std,Z_mean,Z_std,group_mean,group_std,row_mean,row_std,mendeleev_no_mean,mendeleev_no_std,iupac_ordering_mean,iupac_ordering_std,average_ionic_radius_mean,average_ionic_radius_std,atomic_radius_mean,atomic_radius_std,atomic_radius_calculated_mean,atomic_radius_calculated_std,van_der_waals_radius_mean,van_der_waals_radius_std,X_mean,X_std,electron_affinity_mean,electron_affinity_std,ionization_energy_mean,ionization_energy_std,density_of_solid_mean,density_of_solid_std,molar_volume_mean,molar_volume_std,fusion_heat_mean,fusion_heat_std,evaporation_heat_mean,evaporation_heat_std,specific_heat_mean,specific_heat_std,positions
0,"[Ag, Br, S]",Ag3SBr,5.967646,-0.305716,0.098312,0.2964,73.279067,31.299080,32.666667,12.762793,14.666667,2.624669,4.000000,0.816497,87.666667,11.897712,89.333333,12.364825,0.949722,0.096840,1.250000,0.254951,1.156667,0.349698,1.920000,0.135892,2.490000,0.425284,2.248389,0.849311,9.916685,1.758155,5496.545332,3631.543621,15.193333,3.889733,7.916667,4.761634,98.053333,110.615679,0.472333,0.193105,"[(Ag, [7.484018762358994, 2.1052739231579953, ..."
1,"[Ag, I, S]",Ag3SI,6.576090,-0.260466,0.066818,0.5478,88.945890,40.964795,38.666667,16.213849,14.666667,2.624669,4.333333,0.942809,87.333333,11.614168,89.000000,12.083046,1.080000,0.160647,1.333333,0.249444,1.226667,0.318991,1.963333,0.127105,2.390000,0.326905,2.146875,0.717999,9.462501,1.334313,5796.666667,3534.650698,17.173333,6.413581,9.566667,6.072409,102.183333,108.185892,0.385667,0.228085,"[(Ag, [1.9446232162929962, -1.7475588302039966..."
2,"[Ag, I, S]",Ag3SI,6.373934,-0.210889,0.116396,0.6243,88.945890,40.964795,38.666667,16.213849,14.666667,2.624669,4.333333,0.942809,87.333333,11.614168,89.000000,12.083046,1.080000,0.160647,1.333333,0.249444,1.226667,0.318991,1.963333,0.127105,2.390000,0.326905,2.146875,0.717999,9.462501,1.334313,5796.666667,3534.650698,17.173333,6.413581,9.566667,6.072409,102.183333,108.185892,0.385667,0.228085,"[(Ag, [2.504793, 2.504793, 0.0]), (Ag, [2.5047..."
3,"[Ag, As, O]",AgAsO3,5.320520,-1.243946,0.025765,0.5930,66.263067,38.001726,29.333333,16.131405,14.000000,2.160247,3.666667,1.247219,87.000000,12.328828,86.000000,10.424331,1.002222,0.252122,1.116667,0.408928,1.090000,0.478957,1.826667,0.241431,2.516667,0.660824,1.190024,0.280016,10.327613,2.495842,5712.874808,3906.285741,13.526667,2.923062,12.276667,9.800681,97.773333,111.031840,0.494000,0.302259,"[(Ag, [3.6893780804319993, 8.095737138524, 12...."
4,"[Ag, Cl, O]",AgClO3,4.138469,-0.407245,0.038285,2.3983,53.106867,39.528162,24.000000,16.673332,14.666667,2.624669,3.333333,1.247219,90.333333,13.695092,90.000000,12.832251,1.042222,0.198463,1.066667,0.410961,0.973333,0.494930,1.793333,0.242808,2.843333,0.655862,2.126104,1.053143,11.387307,2.707886,4483.441609,4271.691505,15.006667,3.349352,6.266667,4.700031,93.776667,113.501396,0.544000,0.282596,"[(Ag, [0.0, 0.0, 2.42839953268]), (Ag, [0.0, 0..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1419,"[F, Mo, Na, Rb]",Rb2NaMoF6,3.901772,-2.980085,0.000000,4.1434,55.848993,35.079400,24.750000,14.872374,6.250000,6.533567,3.750000,1.299038,44.500000,38.147739,44.250000,38.680583,1.075000,0.379589,1.525000,0.673146,1.717500,0.809271,2.235000,0.552879,1.972500,1.272819,1.295568,1.219509,8.457864,5.281427,3619.071500,3855.162776,25.030000,18.588214,8.337500,11.379961,192.560000,231.924237,0.666500,0.388858,"[(Rb, [6.619406999999999, 6.619406999999999, 6..."
1420,"[F, Na, Rb, Rh]",Rb2NaRhF6,4.194014,-2.638313,0.000000,1.9570,57.590368,37.138772,25.500000,15.771810,7.000000,6.633250,3.750000,1.299038,46.750000,39.015221,46.500000,39.607449,1.067500,0.385689,1.500000,0.677311,1.675000,0.803010,2.217500,0.555760,2.002500,1.278287,1.394481,1.186626,8.549481,5.260082,4161.571500,4792.943375,24.755000,18.824348,6.787500,8.703865,168.560000,190.891937,0.664500,0.391004,"[(Rb, [6.498882, 6.498882, 6.498882]), (Rb, [2..."
1421,"[Cl, Na, Rb, Tm]",Rb2NaTmCl6,3.103076,-2.466064,0.000000,5.0572,78.211195,57.360685,33.500000,22.643984,5.500000,6.689544,4.250000,1.299038,35.000000,37.229021,38.500000,37.619809,1.173750,0.315384,1.725000,0.480234,1.890000,0.688586,2.330000,0.456508,1.540000,0.948552,1.418947,1.283917,7.117037,3.451624,3464.925101,3402.152426,29.007500,15.621683,7.022500,5.899603,106.527500,77.746680,0.557500,0.403599,"[(Rb, [-8.0402235, -8.0402235, -8.0402235]), (..."
1422,"[F, Na, Rb, Y]",Rb2NaYF6,3.583406,-3.568947,0.000000,6.4476,54.090456,33.148734,24.000000,14.035669,5.500000,6.689544,3.750000,1.299038,36.750000,38.173125,42.000000,38.131352,1.141250,0.342790,1.612500,0.680418,1.772500,0.827084,2.272500,0.552285,1.737500,1.302927,1.186581,1.281545,8.239071,5.351129,2167.071500,1357.886469,27.655000,16.853222,4.212500,4.281912,136.810000,137.107546,0.678250,0.376643,"[(Rb, [-2.256712, -2.256712, -2.256712]), (Rb,..."
1423,"[Ag, N, O, Rb]",RbAg(NO3)2,3.319109,-1.056313,0.000000,2.5282,55.835525,41.599394,24.750000,17.612141,10.750000,5.931905,3.500000,1.500000,70.250000,37.358901,67.000000,35.291642,1.159167,0.369552,1.300000,0.725431,1.335000,0.888834,2.052500,0.611325,2.307500,1.021552,0.795376,0.621898,9.976387,4.284475,3494.523167,4045.363750,24.232500,18.374544,3.827500,4.736968,85.575000,101.362932,0.639000,0.345700,"[(Rb, [4.890956488574996, 6.390668282947992, 0..."

In [70]:
elmt = Element("Fe")
#elmt.density_of_solid # in gramm/liter !!!
elmt.atomic_mass/elmt.molar_volume * 1000

7876.586741889985

In [71]:
elemental_properties

{'Ag': {'atomic_mass': 107.8682,
  'Z': 47,
  'group': 11,
  'fusion_heat': 11.95,
  'evaporation_heat': 254.1,
  'specific_heat': 0.235,
  'row': 5,
  'mendeleev_no': 71.0,
  'iupac_ordering': 72,
  'average_ionic_radius': 1.0866666666666667,
  'atomic_radius': 1.6,
  'atomic_radius_calculated': 1.65,
  'van_der_waals_radius': 2.11,
  'X': 1.93,
  'electron_affinity': 1.304473,
  'ionization_energy': 7.576234,
  'density_of_solid': 10490.0,
  'molar_volume': 10.27,
  'boiling_point': 2435.15,
  'melting_point': 1234.93,
  'thermal_conductivity': 430.0},
 'Br': {'atomic_mass': 79.904,
  'Z': 35,
  'group': 17,
  'fusion_heat': 10.57,
  'evaporation_heat': 29.56,
  'specific_heat': 0.474,
  'row': 4,
  'mendeleev_no': 98.0,
  'iupac_ordering': 100,
  'average_ionic_radius': 0.8825000000000001,
  'atomic_radius': 1.15,
  'atomic_radius_calculated': 0.94,
  'van_der_waals_radius': 1.85,
  'X': 2.96,
  'electron_affinity': 3.3635883,
  'ionization_energy': 11.81381,
  'density_of_solid': 4039.6359959555107,
  'molar_volume': 19.78,
  'boiling_point': 331.95,
  'melting_point': 265.8,
  'thermal_conductivity': 0.12},
 'S': {'atomic_mass': 32.065,
  'Z': 16,
  'group': 16,
  'fusion_heat': 1.23,
  'evaporation_heat': 10.5,
  'specific_heat': 0.708,
  'row': 3,
  'mendeleev_no': 94.0,
  'iupac_ordering': 96,
  'average_ionic_radius': 0.88,
  'atomic_radius': 1.0,
  'atomic_radius_calculated': 0.88,
  'van_der_waals_radius': 1.8,
  'X': 2.58,
  'electron_affinity': 2.07710426,
  'ionization_energy': 10.36001,
  'density_of_solid': 1960.0,
  'molar_volume': 15.53,
  'boiling_point': 717.76,
  'melting_point': 388.36,
  'thermal_conductivity': 0.205},
 'I': {'atomic_mass': 126.90447,
  'Z': 53,
  'group': 17,
  'fusion_heat': 15.52,
  'evaporation_heat': 41.95,
  'specific_heat': 0.214,
  'row': 5,
  'mendeleev_no': 97.0,
  'iupac_ordering': 99,
  'average_ionic_radius': 1.2733333333333334,
  'atomic_radius': 1.4,
  'atomic_radius_calculated': 1.15,
  'van_der_waals_radius': 1.98,
  'X': 2.66,
  'electron_affinity': 3.059046537,
  'ionization_energy': 10.45126,
  'density_of_solid': 4940.0,
  'molar_volume': 25.72,
  'boiling_point': 457.54999999999995,
  'melting_point': 386.85,
  'thermal_conductivity': 0.449},
 'As': {'atomic_mass': 74.9216,
  'Z': 33,
  'group': 15,
  'fusion_heat': 24.44,
  'evaporation_heat': 32.4,
  'specific_heat': 0.329,
  'row': 4,
  'mendeleev_no': 89.0,
  'iupac_ordering': 89,
  'average_ionic_radius': 0.6599999999999999,
  'atomic_radius': 1.15,
  'atomic_radius_calculated': 1.14,
  'van_der_waals_radius': 1.85,
  'X': 2.18,
  'electron_affinity': 0.8044863,
  'ionization_energy': 9.78855,
  'density_of_solid': 5727.0,
  'molar_volume': 12.95,
  'boiling_point': 889.15,
  'melting_point': 1090.0,
  'thermal_conductivity': 50.0},
 'O': {'atomic_mass': 15.9994,
  'Z': 8,
  'group': 16,
  'fusion_heat': 0.44,
  'evaporation_heat': 6.82,
  'specific_heat': 0.918,
  'row': 2,
  'mendeleev_no': 101.0,
  'iupac_ordering': 97,
  'average_ionic_radius': 1.26,
  'atomic_radius': 0.6,
  'atomic_radius_calculated': 0.48,
  'van_der_waals_radius': 1.52,
  'X': 3.44,
  'electron_affinity': 1.461112979,
  'ionization_energy': 13.618055,
  'density_of_solid': 921.6244239631336,
  'molar_volume': 17.36,
  'boiling_point': 90.18799999999999,
  'melting_point': 54.8,
  'thermal_conductivity': 0.02658},
 'Cl': {'atomic_mass': 35.453,
  'Z': 17,
  'group': 17,
  'fusion_heat': 6.41,
  'evaporation_heat': 20.41,
  'specific_heat': 0.479,
  'row': 3,
  'mendeleev_no': 99.0,
  'iupac_ordering': 101,
  'average_ionic_radius': 0.7799999999999999,
  'atomic_radius': 1.0,
  'atomic_radius_calculated': 0.79,
  'van_der_waals_radius': 1.75,
  'X': 3.16,
  'electron_affinity': 3.61272528,
  'ionization_energy': 12.967633,
  'density_of_solid': 2038.70040253019,
  'molar_volume': 17.39,
  'boiling_point': 239.10999999999999,
  'melting_point': 171.6,
  'thermal_conductivity': 0.0089},
 'N': {'atomic_mass': 14.0067,
  'Z': 7,
  'group': 15,
  'fusion_heat': 0.72,
  'evaporation_heat': 5.58,
  'specific_heat': 1.04,
  'row': 2,
  'mendeleev_no': 100.0,
  'iupac_ordering': 91,
  'average_ionic_radius': 0.63,
  'atomic_radius': 0.65,
  'atomic_radius_calculated': 0.56,
  'van_der_waals_radius': 1.55,
  'X': 3.04,
  'electron_affinity': -0.07,
  'ionization_energy': 14.53413,
  'density_of_solid': 1034.4682422451995,
  'molar_volume': 13.54,
  'boiling_point': 77.35499999999999,
  'melting_point': 63.05,
  'thermal_conductivity': 0.02583},
 'P': {'atomic_mass': 30.973762,
  'Z': 15,
  'group': 15,
  'fusion_heat': 2.51,
  'evaporation_heat': 49.8,
  'specific_heat': 0.769,
  'row': 3,
  'mendeleev_no': 90.0,
  'iupac_ordering': 90,
  'average_ionic_radius': 0.55,
  'atomic_radius': 1.0,
  'atomic_radius_calculated': 0.98,
  'van_der_waals_radius': 1.8,
  'X': 2.19,
  'electron_affinity': 0.74660911,
  'ionization_energy': 10.486686,
  'density_of_solid': 1823.0,
  'molar_volume': 17.02,
  'boiling_point': 550,
  'melting_point': 317.3,
  'thermal_conductivity': 0.236},
 'Sb': {'atomic_mass': 121.76,
  'Z': 51,
  'group': 15,
  'fusion_heat': 20.08,
  'evaporation_heat': 195.2,
  'specific_heat': 0.207,
  'row': 5,
  'mendeleev_no': 88.0,
  'iupac_ordering': 88,
  'average_ionic_radius': 0.8300000000000001,
  'atomic_radius': 1.45,
  'atomic_radius_calculated': 1.33,
  'van_der_waals_radius': 2.06,
  'X': 2.05,
  'electron_affinity': 1.04740119,
  'ionization_energy': 8.608389,
  'density_of_solid': 6697.0,
  'molar_volume': 18.19,
  'boiling_point': 1860.15,
  'melting_point': 903.78,
  'thermal_conductivity': 24.0},
 'Se': {'atomic_mass': 78.96,
  'Z': 34,
  'group': 16,
  'fusion_heat': 5.23,
  'evaporation_heat': 59.7,
  'specific_heat': 0.321,
  'row': 4,
  'mendeleev_no': 93.0,
  'iupac_ordering': 95,
  'average_ionic_radius': 1.0133333333333334,
  'atomic_radius': 1.15,
  'atomic_radius_calculated': 1.03,
  'van_der_waals_radius': 1.9,
  'X': 2.55,
  'electron_affinity': 2.020604712,
  'ionization_energy': 9.752392,
  'density_of_solid': 4819.0,
  'molar_volume': 16.42,
  'boiling_point': 958.15,
  'melting_point': 494.0,
  'thermal_conductivity': 0.52},
 'Te': {'atomic_mass': 127.6,
  'Z': 52,
  'group': 16,
  'fusion_heat': 17.91,
  'evaporation_heat': 49.8,
  'specific_heat': 0.202,
  'row': 5,
  'mendeleev_no': 92.0,
  'iupac_ordering': 94,
  'average_ionic_radius': 1.2933333333333332,
  'atomic_radius': 1.4,
  'atomic_radius_calculated': 1.23,
  'van_der_waals_radius': 2.06,
  'X': 2.1,
  'electron_affinity': 1.9708757,
  'ionization_energy': 9.009808,
  'density_of_solid': 6240.0,
  'molar_volume': 20.46,
  'boiling_point': 1261.15,
  'melting_point': 722.66,
  'thermal_conductivity': 3.0},
 'Al': {'atomic_mass': 26.9815386,
  'Z': 13,
  'group': 13,
  'fusion_heat': 10.75,
  'evaporation_heat': 284.1,
  'specific_heat': 0.897,
  'row': 3,
  'mendeleev_no': 80.0,
  'iupac_ordering': 80,
  'average_ionic_radius': 0.675,
  'atomic_radius': 1.25,
  'atomic_radius_calculated': 1.18,
  'van_der_waals_radius': 1.84,
  'X': 1.61,
  'electron_affinity': 0.432835,
  'ionization_energy': 5.985769,
  'density_of_solid': 2700.0,
  'molar_volume': 10.0,
  'boiling_point': 2792.15,
  'melting_point': 933.47,
  'thermal_conductivity': 235.0},
 'B': {'atomic_mass': 10.811,
  'Z': 5,
  'group': 13,
  'fusion_heat': 23.6,
  'evaporation_heat': 504.5,
  'specific_heat': 1.026,
  'row': 2,
  'mendeleev_no': 86.0,
  'iupac_ordering': 81,
  'average_ionic_radius': 0.41,
  'atomic_radius': 0.85,
  'atomic_radius_calculated': 0.87,
  'van_der_waals_radius': 1.92,
  'X': 2.04,
  'electron_affinity': 0.27972325,
  'ionization_energy': 8.298019,
  'density_of_solid': 2460.0,
  'molar_volume': 4.39,
  'boiling_point': 4273.15,
  'melting_point': 2349.0,
  'thermal_conductivity': 27.0},
 'Bi': {'atomic_mass': 208.9804,
  'Z': 83,
  'group': 15,
  'fusion_heat': 11.0,
  'evaporation_heat': 172.0,
  'specific_heat': 0.122,
  'row': 6,
  'mendeleev_no': 87.0,
  'iupac_ordering': 87,
  'average_ionic_radius': 1.035,
  'atomic_radius': 1.6,
  'atomic_radius_calculated': 1.43,
  'van_der_waals_radius': 2.07,
  'X': 2.02,
  'electron_affinity': 0.94236213,
  'ionization_energy': 7.285516,
  'density_of_solid': 9780.0,
  'molar_volume': 21.31,
  'boiling_point': 1837.15,
  'melting_point': 544.4,
  'thermal_conductivity': 8.0},
 'Fe': {'atomic_mass': 55.845,
  'Z': 26,
  'group': 8,
  'fusion_heat': 13.8,
  'evaporation_heat': 340.0,
  'specific_heat': 0.449,
  'row': 4,
  'mendeleev_no': 61.0,
  'iupac_ordering': 64,
  'average_ionic_radius': 0.8525,
  'atomic_radius': 1.4,
  'atomic_radius_calculated': 1.56,
  'van_der_waals_radius': 2.04,
  'X': 1.83,
  'electron_affinity': 0.15323635,
  'ionization_energy': 7.9024681,
  'density_of_solid': 7874.0,
  'molar_volume': 7.09,
  'boiling_point': 3134.15,
  'melting_point': 1811.0,
  'thermal_conductivity': 80.0},
 'Si': {'atomic_mass': 28.0855,
  'Z': 14,
  'group': 14,
  'fusion_heat': 50.6,
  'evaporation_heat': 383.0,
  'specific_heat': 0.712,
  'row': 3,
  'mendeleev_no': 85.0,
  'iupac_ordering': 85,
  'average_ionic_radius': 0.54,
  'atomic_radius': 1.1,
  'atomic_radius_calculated': 1.11,
  'van_der_waals_radius': 2.1,
  'X': 1.9,
  'electron_affinity': 1.38952128,
  'ionization_energy': 8.15168,
  'density_of_solid': 2330.0,
  'molar_volume': 12.06,
  'boiling_point': 3538.15,
  'melting_point': 1687.0,
  'thermal_conductivity': 150.0},
 'C': {'atomic_mass': 12.0107,
  'Z': 6,
  'group': 14,
  'fusion_heat': 117,
  'evaporation_heat': 715,
  'specific_heat': 0.709,
  'row': 2,
  'mendeleev_no': 95.0,
  'iupac_ordering': 86,
  'average_ionic_radius': 0.3,
  'atomic_radius': 0.7,
  'atomic_radius_calculated': 0.67,
  'van_der_waals_radius': 1.7,
  'X': 2.55,
  'electron_affinity': 1.262122611,
  'ionization_energy': 11.260288,
  'density_of_solid': 2267.0,
  'molar_volume': 5.29,
  'boiling_point': 4098.15,
  'melting_point': 3800.0,
  'thermal_conductivity': 140.0},
 'F': {'atomic_mass': 18.9984032,
  'Z': 9,
  'group': 17,
  'fusion_heat': 0.51,
  'evaporation_heat': 6.54,
  'specific_heat': 0.824,
  'row': 2,
  'mendeleev_no': 102.0,
  'iupac_ordering': 102,
  'average_ionic_radius': 0.705,
  'atomic_radius': 0.5,
  'atomic_radius_calculated': 0.42,
  'van_der_waals_radius': 1.47,
  'X': 3.98,
  'electron_affinity': 3.401189824,
  'ionization_energy': 17.42282,
  'density_of_solid': 1696.286,
  'molar_volume': 11.2,
  'boiling_point': 85.03999999999996,
  'melting_point': 53.53,
  'thermal_conductivity': 0.0277},
 'Ba': {'atomic_mass': 137.327,
  'Z': 56,
  'group': 2,
  'fusion_heat': 7.66,
  'evaporation_heat': 142.0,
  'specific_heat': 0.204,
  'row': 6,
  'mendeleev_no': 14.0,
  'iupac_ordering': 13,
  'average_ionic_radius': 1.49,
  'atomic_radius': 2.15,
  'atomic_radius_calculated': 2.53,
  'van_der_waals_radius': 2.68,
  'X': 0.89,
  'electron_affinity': 0.144626,
  'ionization_energy': 5.2116646,
  'density_of_solid': 3510.0,
  'molar_volume': 38.16,
  'boiling_point': 2118.15,
  'melting_point': 1000.0,
  'thermal_conductivity': 18.0},
 'Ge': {'atomic_mass': 72.64,
  'Z': 32,
  'group': 14,
  'fusion_heat': 36.8,
  'evaporation_heat': 328.0,
  'specific_heat': 0.32,
  'row': 4,
  'mendeleev_no': 84.0,
  'iupac_ordering': 84,
  'average_ionic_radius': 0.77,
  'atomic_radius': 1.25,
  'atomic_radius_calculated': 1.25,
  'van_der_waals_radius': 2.11,
  'X': 2.01,
  'electron_affinity': 1.232676413,
  'ionization_energy': 7.899435,
  'density_of_solid': 5323.0,
  'molar_volume': 13.63,
  'boiling_point': 3106.15,
  'melting_point': 1211.4,
  'thermal_conductivity': 60.0},
 'Ce': {'atomic_mass': 140.116,
  'Z': 58,
  'group': 3,
  'fusion_heat': 5.2,
  'evaporation_heat': 398.0,
  'specific_heat': 0.192,
  'row': 6,
  'mendeleev_no': 32.0,
  'iupac_ordering': 46,
  'average_ionic_radius': 1.08,
  'atomic_radius': 1.85,
  'atomic_radius_calculated': 1.85,
  'van_der_waals_radius': 2.42,
  'X': 1.12,
  'electron_affinity': 0.60016027,
  'ionization_energy': 5.5386,
  'density_of_solid': 6689.0,
  'molar_volume': 20.69,
  'boiling_point': 3716.15,
  'melting_point': 1068.0,
  'thermal_conductivity': 11.0},
 'Hf': {'atomic_mass': 178.49,
  'Z': 72,
  'group': 4,
  'fusion_heat': 25.1,
  'evaporation_heat': 575.0,
  'specific_heat': 0.144,
  'row': 6,
  'mendeleev_no': 50.0,
  'iupac_ordering': 50,
  'average_ionic_radius': 0.85,
  'atomic_radius': 1.55,
  'atomic_radius_calculated': 2.08,
  'van_der_waals_radius': 2.23,
  'X': 1.3,
  'electron_affinity': 0.17807,
  'ionization_energy': 6.82507,
  'density_of_solid': 13310.0,
  'molar_volume': 13.44,
  'boiling_point': 4873.15,
  'melting_point': 2506.0,
  'thermal_conductivity': 23.0},
 'Li': {'atomic_mass': 6.941,
  'Z': 3,
  'group': 1,
  'fusion_heat': 2.89,
  'evaporation_heat': 148.0,
  'specific_heat': 3.582,
  'row': 2,
  'mendeleev_no': 12.0,
  'iupac_ordering': 11,
  'average_ionic_radius': 0.9,
  'atomic_radius': 1.45,
  'atomic_radius_calculated': 1.67,
  'van_der_waals_radius': 1.82,
  'X': 0.98,
  'electron_affinity': 0.61804922,
  'ionization_energy': 5.391714996,
  'density_of_solid': 535.0,
  'molar_volume': 13.02,
  'boiling_point': 1615.15,
  'melting_point': 453.69,
  'thermal_conductivity': 85.0},
 'H': {'atomic_mass': 1.00794,
  'Z': 1,
  'group': 1,
  'fusion_heat': 0.117,
  'evaporation_heat': 0.904,
  'specific_heat': 14.304,
  'row': 1,
  'mendeleev_no': 103.0,
  'iupac_ordering': 92,
  'average_ionic_radius': 0.0,
  'atomic_radius': 0.25,
  'atomic_radius_calculated': 0.53,
  'van_der_waals_radius': 1.1,
  'X': 2.2,
  'electron_affinity': 0.75419519,
  'ionization_energy': 13.598434599702,
  'density_of_solid': 88.26094570928197,
  'molar_volume': 11.42,
  'boiling_point': 20.270999999999987,
  'melting_point': 14.01,
  'thermal_conductivity': 0.1805},
 'Mn': {'atomic_mass': 54.938045,
  'Z': 25,
  'group': 7,
  'fusion_heat': 13.4,
  'evaporation_heat': 221.0,
  'specific_heat': 0.479,
  'row': 4,
  'mendeleev_no': 60.0,
  'iupac_ordering': 61,
  'average_ionic_radius': 0.8775,
  'atomic_radius': 1.4,
  'atomic_radius_calculated': 1.61,
  'van_der_waals_radius': 2.05,
  'X': 1.55,
  'electron_affinity': -0.52,
  'ionization_energy': 7.434038,
  'density_of_solid': 7470.0,
  'molar_volume': 7.35,
  'boiling_point': 2334.15,
  'melting_point': 1519.0,
  'thermal_conductivity': 7.8},
 'Ni': {'atomic_mass': 58.6934,
  'Z': 28,
  'group': 10,
  'fusion_heat': 17.61,
  'evaporation_heat': 378.6,
  'specific_heat': 0.444,
  'row': 4,
  'mendeleev_no': 67.0,
  'iupac_ordering': 70,
  'average_ionic_radius': 0.74,
  'atomic_radius': 1.35,
  'atomic_radius_calculated': 1.49,
  'van_der_waals_radius': 1.97,
  'X': 1.91,
  'electron_affinity': 1.1571612,
  'ionization_energy': 7.639878,
  'density_of_solid': 8908.0,
  'molar_volume': 6.59,
  'boiling_point': 3186.15,
  'melting_point': 1728.0,
  'thermal_conductivity': 91.0},
 'Pb': {'atomic_mass': 207.2,
  'Z': 82,
  'group': 14,
  'fusion_heat': 4.77,
  'evaporation_heat': 177.8,
  'specific_heat': 0.13,
  'row': 6,
  'mendeleev_no': 82.0,
  'iupac_ordering': 82,
  'average_ionic_radius': 1.1225,
  'atomic_radius': 1.8,
  'atomic_radius_calculated': 1.54,
  'van_der_waals_radius': 2.02,
  'X': 2.33,
  'electron_affinity': 0.3567212,
  'ionization_energy': 7.4166799,
  'density_of_solid': 11340.0,
  'molar_volume': 18.26,
  'boiling_point': 2022.15,
  'melting_point': 600.61,
  'thermal_conductivity': 35.0},
 'Sn': {'atomic_mass': 118.71,
  'Z': 50,
  'group': 14,
  'fusion_heat': 7.07,
  'evaporation_heat': 296.0,
  'specific_heat': 0.227,
  'row': 5,
  'mendeleev_no': 83.0,
  'iupac_ordering': 83,
  'average_ionic_radius': 0.83,
  'atomic_radius': 1.45,
  'atomic_radius_calculated': 1.45,
  'van_der_waals_radius': 2.17,
  'X': 1.96,
  'electron_affinity': 1.1120702,
  'ionization_energy': 7.343918,
  'density_of_solid': 7310.0,
  'molar_volume': 16.29,
  'boiling_point': 2859.15,
  'melting_point': 505.08,
  'thermal_conductivity': 67.0},
 'Th': {'atomic_mass': 232.03806,
  'Z': 90,
  'group': 3,
  'fusion_heat': 16.11,
  'evaporation_heat': 513.7,
  'specific_heat': 0.118,
  'row': 7,
  'mendeleev_no': 47.0,
  'iupac_ordering': 31,
  'average_ionic_radius': 1.08,
  'atomic_radius': 1.8,
  'atomic_radius_calculated': 1.8,
  'van_der_waals_radius': 2.45,
  'X': 1.3,
  'electron_affinity': 0.607696,
  'ionization_energy': 6.3067,
  'density_of_solid': 11724.0,
  'molar_volume': 19.8,
  'boiling_point': 5058.15,
  'melting_point': 2115.0,
  'thermal_conductivity': 54.0},
 'Ti': {'atomic_mass': 47.867,
  'Z': 22,
  'group': 4,
  'fusion_heat': 18.8,
  'evaporation_heat': 422.6,
  'specific_heat': 0.523,
  'row': 4,
  'mendeleev_no': 51.0,
  'iupac_ordering': 52,
  'average_ionic_radius': 0.8516666666666667,
  'atomic_radius': 1.4,
  'atomic_radius_calculated': 1.76,
  'van_der_waals_radius': 2.11,
  'X': 1.54,
  'electron_affinity': 0.075545,
  'ionization_energy': 6.82812,
  'density_of_solid': 4507.0,
  'molar_volume': 10.64,
  'boiling_point': 3560.15,
  'melting_point': 1941.0,
  'thermal_conductivity': 22.0},
 'Zr': {'atomic_mass': 91.224,
  'Z': 40,
  'group': 4,
  'fusion_heat': 19.2,
  'evaporation_heat': 567.0,
  'specific_heat': 0.278,
  'row': 5,
  'mendeleev_no': 49.0,
  'iupac_ordering': 51,
  'average_ionic_radius': 0.86,
  'atomic_radius': 1.55,
  'atomic_radius_calculated': 2.06,
  'van_der_waals_radius': 2.23,
  'X': 1.33,
  'electron_affinity': 0.433289,
  'ionization_energy': 6.634126,
  'density_of_solid': 6511.0,
  'molar_volume': 14.02,
  'boiling_point': 4679.15,
  'melting_point': 2128.0,
  'thermal_conductivity': 23.0},
 'Be': {'atomic_mass': 9.012182,
  'Z': 4,
  'group': 2,
  'fusion_heat': 12.21,
  'evaporation_heat': 309.0,
  'specific_heat': 1.825,
  'row': 2,
  'mendeleev_no': 77.0,
  'iupac_ordering': 17,
  'average_ionic_radius': 0.59,
  'atomic_radius': 1.05,
  'atomic_radius_calculated': 1.12,
  'van_der_waals_radius': 1.53,
  'X': 1.57,
  'electron_affinity': -0.52,
  'ionization_energy': 9.322699,
  'density_of_solid': 1848.0,
  'molar_volume': 4.85,
  'boiling_point': 2741.15,
  'melting_point': 1560.0,
  'thermal_conductivity': 190.0},
 'Rh': {'atomic_mass': 102.9055,
  'Z': 45,
  'group': 9,
  'fusion_heat': 21.8,
  'evaporation_heat': 494.0,
  'specific_heat': 0.243,
  'row': 5,
  'mendeleev_no': 65.0,
  'iupac_ordering': 66,
  'average_ionic_radius': 0.745,
  'atomic_radius': 1.35,
  'atomic_radius_calculated': 1.73,
  'van_der_waals_radius': 2.1,
  'X': 2.28,
  'electron_affinity': 1.142892,
  'ionization_energy': 7.4589,
  'density_of_solid': 12450.0,
  'molar_volume': 8.28,
  'boiling_point': 3968.15,
  'melting_point': 2237.0,
  'thermal_conductivity': 150.0},
 'Ca': {'atomic_mass': 40.078,
  'Z': 20,
  'group': 2,
  'fusion_heat': 9.2,
  'evaporation_heat': 153.6,
  'specific_heat': 0.647,
  'row': 4,
  'mendeleev_no': 16.0,
  'iupac_ordering': 15,
  'average_ionic_radius': 1.14,
  'atomic_radius': 1.8,
  'atomic_radius_calculated': 1.94,
  'van_der_waals_radius': 2.31,
  'X': 1,
  'electron_affinity': 0.024551,
  'ionization_energy': 6.11315547,
  'density_of_solid': 1550.0,
  'molar_volume': 26.2,
  'boiling_point': 1757.15,
  'melting_point': 1115.0,
  'thermal_conductivity': 200.0},
 'Cr': {'atomic_mass': 51.9961,
  'Z': 24,
  'group': 6,
  'fusion_heat': 21.0,
  'evaporation_heat': 342.0,
  'specific_heat': 0.449,
  'row': 4,
  'mendeleev_no': 57.0,
  'iupac_ordering': 58,
  'average_ionic_radius': 0.94,
  'atomic_radius': 1.4,
  'atomic_radius_calculated': 1.66,
  'van_der_waals_radius': 2.06,
  'X': 1.66,
  'electron_affinity': 0.67592827,
  'ionization_energy': 6.76651,
  'density_of_solid': 7140.0,
  'molar_volume': 7.23,
  'boiling_point': 2944.15,
  'melting_point': 2180.0,
  'thermal_conductivity': 94.0},
 'In': {'atomic_mass': 114.818,
  'Z': 49,
  'group': 13,
  'fusion_heat': 3.24,
  'evaporation_heat': 225.1,
  'specific_heat': 0.233,
  'row': 5,
  'mendeleev_no': 79.0,
  'iupac_ordering': 78,

In [72]:
# rename df again
df = df_curated
#print dataframe to csv
df.to_csv('A2BCX6_filtered_with_properties.csv', index = False)

In [73]:
from ase import Atoms

#Setting up Atomic Simulation Environment (ASE)
def get_ase(df):
    df["ase"] = None  # Optional, for clarity
    for i, row in df.iterrows():
        symbols = [atom[0] for atom in row["positions"]]
        positions = [atom[1] for atom in row["positions"]]

        atoms_obj = Atoms(symbols=symbols, positions=positions)
        df.at[i, "ase"] = atoms_obj
    return df

df = get_ase(df)
print(df["ase"])

0       (Atom('Ag', [np.float64(7.484018762358994), np...
1       (Atom('Ag', [np.float64(1.9446232162929962), n...
2       (Atom('Ag', [np.float64(2.504793), np.float64(...
3       (Atom('Ag', [np.float64(3.6893780804319993), n...
4       (Atom('Ag', [np.float64(0.0), np.float64(0.0),...
                              ...
1419    (Atom('Rb', [np.float64(6.619406999999999), np...
1420    (Atom('Rb', [np.float64(6.498882), np.float64(...
1421    (Atom('Rb', [np.float64(-8.0402235), np.float6...
1422    (Atom('Rb', [np.float64(-2.256712), np.float64...
1423    (Atom('Rb', [np.float64(4.890956488574996), np...
Name: ase, Length: 1424, dtype: object

In [74]:
from dscribe.descriptors import SOAP
import numpy as np

def get_soap(df, r_cut=190.0, n_max=2, l_max=2, sigma=1):
    # Automatically extract all unique species from df["Elements"]
    unique_species = sorted(set(e for row in df["elements"] for e in row))

    # Create SOAP descriptor generator
    soap_generator = SOAP(
        species=unique_species,
        r_cut=r_cut,
        n_max=n_max,
        l_max=l_max,
        sigma=sigma,
        periodic=False,
        sparse=False,
        rbf = "gto"
    )

    # Generate and store SOAP descriptors
    soap_list = []
    for atoms in df["ase"]:
        descriptor = soap_generator.create(atoms)
        #this seems to make every soap have the same length
        avg_descriptor = np.mean(descriptor, axis=0) #check if this is the correct way to do it with stehpan

        soap_list.append(avg_descriptor)

    df["soap"] = soap_list
    return df

# Get SOAP descriptors from
df_soap = get_soap(df)
df_soap.to_csv("df_soap.csv", index=False)
df_soap_nonzero = df_soap["soap"].apply(lambda x: x.nonzero()[0])
print(df_soap_nonzero.shape)
print(df_soap.shape)

(1424,)
(1424, 45)

In [75]:
df_soap

,elements,formula_pretty,density,formation_energy_per_atom,energy_above_hull,band_gap,atom_mass_mean,atom_mass_std,Z_mean,Z_std,group_mean,group_std,row_mean,row_std,mendeleev_no_mean,mendeleev_no_std,iupac_ordering_mean,iupac_ordering_std,average_ionic_radius_mean,average_ionic_radius_std,atomic_radius_mean,atomic_radius_std,atomic_radius_calculated_mean,atomic_radius_calculated_std,van_der_waals_radius_mean,van_der_waals_radius_std,X_mean,X_std,electron_affinity_mean,electron_affinity_std,ionization_energy_mean,ionization_energy_std,density_of_solid_mean,density_of_solid_std,molar_volume_mean,molar_volume_std,fusion_heat_mean,fusion_heat_std,evaporation_heat_mean,evaporation_heat_std,specific_heat_mean,specific_heat_std,positions,ase,soap
0,"[Ag, Br, S]",Ag3SBr,5.967646,-0.305716,0.098312,0.2964,73.279067,31.299080,32.666667,12.762793,14.666667,2.624669,4.000000,0.816497,87.666667,11.897712,89.333333,12.364825,0.949722,0.096840,1.250000,0.254951,1.156667,0.349698,1.920000,0.135892,2.490000,0.425284,2.248389,0.849311,9.916685,1.758155,5496.545332,3631.543621,15.193333,3.889733,7.916667,4.761634,98.053333,110.615679,0.472333,0.193105,"[(Ag, [7.484018762358994, 2.1052739231579953, ...","(Atom('Ag', [np.float64(7.484018762358994), np...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1,"[Ag, I, S]",Ag3SI,6.576090,-0.260466,0.066818,0.5478,88.945890,40.964795,38.666667,16.213849,14.666667,2.624669,4.333333,0.942809,87.333333,11.614168,89.000000,12.083046,1.080000,0.160647,1.333333,0.249444,1.226667,0.318991,1.963333,0.127105,2.390000,0.326905,2.146875,0.717999,9.462501,1.334313,5796.666667,3534.650698,17.173333,6.413581,9.566667,6.072409,102.183333,108.185892,0.385667,0.228085,"[(Ag, [1.9446232162929962, -1.7475588302039966...","(Atom('Ag', [np.float64(1.9446232162929962), n...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
2,"[Ag, I, S]",Ag3SI,6.373934,-0.210889,0.116396,0.6243,88.945890,40.964795,38.666667,16.213849,14.666667,2.624669,4.333333,0.942809,87.333333,11.614168,89.000000,12.083046,1.080000,0.160647,1.333333,0.249444,1.226667,0.318991,1.963333,0.127105,2.390000,0.326905,2.146875,0.717999,9.462501,1.334313,5796.666667,3534.650698,17.173333,6.413581,9.566667,6.072409,102.183333,108.185892,0.385667,0.228085,"[(Ag, [2.504793, 2.504793, 0.0]), (Ag, [2.5047...","(Atom('Ag', [np.float64(2.504793), np.float64(...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
3,"[Ag, As, O]",AgAsO3,5.320520,-1.243946,0.025765,0.5930,66.263067,38.001726,29.333333,16.131405,14.000000,2.160247,3.666667,1.247219,87.000000,12.328828,86.000000,10.424331,1.002222,0.252122,1.116667,0.408928,1.090000,0.478957,1.826667,0.241431,2.516667,0.660824,1.190024,0.280016,10.327613,2.495842,5712.874808,3906.285741,13.526667,2.923062,12.276667,9.800681,97.773333,111.031840,0.494000,0.302259,"[(Ag, [3.6893780804319993, 8.095737138524, 12....","(Atom('Ag', [np.float64(3.6893780804319993), n...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
4,"[Ag, Cl, O]",AgClO3,4.138469,-0.407245,0.038285,2.3983,53.106867,39.528162,24.000000,16.673332,14.666667,2.624669,3.333333,1.247219,90.333333,13.695092,90.000000,12.832251,1.042222,0.198463,1.066667,0.410961,0.973333,0.494930,1.793333,0.242808,2.843333,0.655862,2.126104,1.053143,11.387307,2.707886,4483.441609,4271.691505,15.006667,3.349352,6.266667,4.700031,93.776667,113.501396,0.544000,0.282596,"[(Ag, [0.0, 0.0, 2.42839953268]), (Ag, [0.0, 0...","(Atom('Ag', [np.float64(0.0), np.float64(0.0),...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1419,"[F, Mo, Na, Rb]",Rb2NaMoF6,3.901772,-2.980085,0.000000,4.1434,55.848993,35.079400,24.750000,14.872374,6.250000,6.533567,3.750000,1.299038,44.500000,38.147739,44.250000,38.680583,1.075000,0.379589,1.525000,0.673146,1.717500,0.809271,2.235000,0.552879,1.972500,1.272819,1.295568,1.219509,8.457864,5.281427,3619.071500,3855.162776,25.030000,18.588214,8.337500,11.379961,192.560000,231.924237,0.666500,0.388858,"[(Rb, [6.619406999999999, 6.619406999999999, 6...","(Atom('Rb', [np.float64(6.619406999999999), np...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1420,"[F, Na, Rb, Rh]",Rb2NaRhF6,4.194014,-2.638313,0.000000,1.9570,57.590368,37.138772,25.500000,15.771810,7.000000,6.633250,3.750000,1.299038,46.750000,39.015221,46.500000,39.607449,1.067500,0.385689,1.500000,0.677311,1.675000,0.803010,2.217500,0.555760,2.002500,1.278287,1.394481,1.186626,8.549481,5.260082,4161.571500,4792.943375,24.755000,18.824348,6.787500,8.703865,168.560000,190.891937,0.664500,0.391004,"[(Rb, [6.498882, 6.498882, 6.498882]), (Rb, [2...","(Atom('Rb', [np.float64(6.498882), np.float64(...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1421,"[Cl, Na, Rb, Tm]",Rb2NaTmCl6,3.103076,-2.466064,0.000000,5.0572,78.211195,57.360685,33.500000,22.643984,5.500000,6.689544,4.250000,1.299038,35.000000,37.229021,38.500000,37.619809,1.173750,0.315384,1.725000,0.480234,1.890000,0.688586,2.330000,0.456508,1.540000,0.948552,1.418947,1.283917,7.117037,3.451624,3464.925101,3402.152426,29.007500,15.621683,7.022500,5.899603,106.527500,77.746680,0.557500,0.403599,"[(Rb, [-8.0402235, -8.0402235, -8.0402235]), (...","(Atom('Rb', [np.float64(-8.0402235), np.float6...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1422,"[F, Na, Rb, Y]",Rb2NaYF6,3.583406,-3.568947,0.000000,6.4476,54.090456,33.148734,24.000000,14.035669,5.500000,6.689544,3.750000,1.299038,36.750000,38.173125,42.000000,38.131352,1.141250,0.342790,1.612500,0.680418,1.772500,0.827084,2.272500,0.552285,1.737500,1.302927,1.186581,1.281545,8.239071,5.351129,2167.071500,1357.886469,27.655000,16.853222,4.212500,4.281912,136.810000,137.107546,0.678250,0.376643,"[(Rb, [-2.256712, -2.256712, -2.256712]), (Rb,...","(Atom('Rb', [np.float64(-2.256712), np.float64...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1423,"[Ag, N, O, Rb]",RbAg(NO3)2,3.319109,-1.056313,0.000000,2.5282,55.835525,41.599394,24.750000,17.612141,10.750000,5.931905,3.500000,1.500000,70.250000,37.358901,67.000000,35.291642,1.159167,0.369552,1.300000,0.725431,1.335000,0.888834,2.052500,0.611325,2.307500,1.021552,0.795376,0.621898,9.976387,4.284475,3494.523167,4045.363750,24.232500,18.374544,3.827500,4.736968,85.575000,101.362932,0.639000,0.345700,"[(Rb, [4.890956488574996, 6.390668282947992, 0...","(Atom('Rb', [np.float64(4.890956488574996), np...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."

In [83]:
# Prepare x array from the SOAP descriptors
df = df_soap
df = df.drop(columns=["ase","positions"])
#df = pd.read_csv('combine.csv') #Combined ABX3 and A2BB'X6 Perovskite Structures.

X = df.drop(columns = ["band_gap"])
df['band_gap'] = df['band_gap'].astype('float64')
y = np.asarray(df['band_gap']) # Code simulated for predicting the energy bandgap.

X
y

array([0.2964, 0.5478, 0.6243, ..., 5.0572, 6.4476, 2.5282], shape=(1424,))

In [81]:
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
df

,elements,formula_pretty,density,formation_energy_per_atom,energy_above_hull,band_gap,atom_mass_mean,atom_mass_std,Z_mean,Z_std,group_mean,group_std,row_mean,row_std,mendeleev_no_mean,mendeleev_no_std,iupac_ordering_mean,iupac_ordering_std,average_ionic_radius_mean,average_ionic_radius_std,atomic_radius_mean,atomic_radius_std,atomic_radius_calculated_mean,atomic_radius_calculated_std,van_der_waals_radius_mean,van_der_waals_radius_std,X_mean,X_std,electron_affinity_mean,electron_affinity_std,ionization_energy_mean,ionization_energy_std,density_of_solid_mean,density_of_solid_std,molar_volume_mean,molar_volume_std,fusion_heat_mean,fusion_heat_std,evaporation_heat_mean,evaporation_heat_std,specific_heat_mean,specific_heat_std,soap
0,"[Ag, Br, S]",Ag3SBr,5.967646,-0.305716,0.098312,0.2964,73.279067,31.299080,32.666667,12.762793,14.666667,2.624669,4.000000,0.816497,87.666667,11.897712,89.333333,12.364825,0.949722,0.096840,1.250000,0.254951,1.156667,0.349698,1.920000,0.135892,2.490000,0.425284,2.248389,0.849311,9.916685,1.758155,5496.545332,3631.543621,15.193333,3.889733,7.916667,4.761634,98.053333,110.615679,0.472333,0.193105,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1,"[Ag, I, S]",Ag3SI,6.576090,-0.260466,0.066818,0.5478,88.945890,40.964795,38.666667,16.213849,14.666667,2.624669,4.333333,0.942809,87.333333,11.614168,89.000000,12.083046,1.080000,0.160647,1.333333,0.249444,1.226667,0.318991,1.963333,0.127105,2.390000,0.326905,2.146875,0.717999,9.462501,1.334313,5796.666667,3534.650698,17.173333,6.413581,9.566667,6.072409,102.183333,108.185892,0.385667,0.228085,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
2,"[Ag, I, S]",Ag3SI,6.373934,-0.210889,0.116396,0.6243,88.945890,40.964795,38.666667,16.213849,14.666667,2.624669,4.333333,0.942809,87.333333,11.614168,89.000000,12.083046,1.080000,0.160647,1.333333,0.249444,1.226667,0.318991,1.963333,0.127105,2.390000,0.326905,2.146875,0.717999,9.462501,1.334313,5796.666667,3534.650698,17.173333,6.413581,9.566667,6.072409,102.183333,108.185892,0.385667,0.228085,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
3,"[Ag, As, O]",AgAsO3,5.320520,-1.243946,0.025765,0.5930,66.263067,38.001726,29.333333,16.131405,14.000000,2.160247,3.666667,1.247219,87.000000,12.328828,86.000000,10.424331,1.002222,0.252122,1.116667,0.408928,1.090000,0.478957,1.826667,0.241431,2.516667,0.660824,1.190024,0.280016,10.327613,2.495842,5712.874808,3906.285741,13.526667,2.923062,12.276667,9.800681,97.773333,111.031840,0.494000,0.302259,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
4,"[Ag, Cl, O]",AgClO3,4.138469,-0.407245,0.038285,2.3983,53.106867,39.528162,24.000000,16.673332,14.666667,2.624669,3.333333,1.247219,90.333333,13.695092,90.000000,12.832251,1.042222,0.198463,1.066667,0.410961,0.973333,0.494930,1.793333,0.242808,2.843333,0.655862,2.126104,1.053143,11.387307,2.707886,4483.441609,4271.691505,15.006667,3.349352,6.266667,4.700031,93.776667,113.501396,0.544000,0.282596,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1419,"[F, Mo, Na, Rb]",Rb2NaMoF6,3.901772,-2.980085,0.000000,4.1434,55.848993,35.079400,24.750000,14.872374,6.250000,6.533567,3.750000,1.299038,44.500000,38.147739,44.250000,38.680583,1.075000,0.379589,1.525000,0.673146,1.717500,0.809271,2.235000,0.552879,1.972500,1.272819,1.295568,1.219509,8.457864,5.281427,3619.071500,3855.162776,25.030000,18.588214,8.337500,11.379961,192.560000,231.924237,0.666500,0.388858,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1420,"[F, Na, Rb, Rh]",Rb2NaRhF6,4.194014,-2.638313,0.000000,1.9570,57.590368,37.138772,25.500000,15.771810,7.000000,6.633250,3.750000,1.299038,46.750000,39.015221,46.500000,39.607449,1.067500,0.385689,1.500000,0.677311,1.675000,0.803010,2.217500,0.555760,2.002500,1.278287,1.394481,1.186626,8.549481,5.260082,4161.571500,4792.943375,24.755000,18.824348,6.787500,8.703865,168.560000,190.891937,0.664500,0.391004,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1421,"[Cl, Na, Rb, Tm]",Rb2NaTmCl6,3.103076,-2.466064,0.000000,5.0572,78.211195,57.360685,33.500000,22.643984,5.500000,6.689544,4.250000,1.299038,35.000000,37.229021,38.500000,37.619809,1.173750,0.315384,1.725000,0.480234,1.890000,0.688586,2.330000,0.456508,1.540000,0.948552,1.418947,1.283917,7.117037,3.451624,3464.925101,3402.152426,29.007500,15.621683,7.022500,5.899603,106.527500,77.746680,0.557500,0.403599,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1422,"[F, Na, Rb, Y]",Rb2NaYF6,3.583406,-3.568947,0.000000,6.4476,54.090456,33.148734,24.000000,14.035669,5.500000,6.689544,3.750000,1.299038,36.750000,38.173125,42.000000,38.131352,1.141250,0.342790,1.612500,0.680418,1.772500,0.827084,2.272500,0.552285,1.737500,1.302927,1.186581,1.281545,8.239071,5.351129,2167.071500,1357.886469,27.655000,16.853222,4.212500,4.281912,136.810000,137.107546,0.678250,0.376643,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1423,"[Ag, N, O, Rb]",RbAg(NO3)2,3.319109,-1.056313,0.000000,2.5282,55.835525,41.599394,24.750000,17.612141,10.750000,5.931905,3.500000,1.500000,70.250000,37.358901,67.000000,35.291642,1.159167,0.369552,1.300000,0.725431,1.335000,0.888834,2.052500,0.611325,2.307500,1.021552,0.795376,0.621898,9.976387,4.284475,3494.523167,4045.363750,24.232500,18.374544,3.827500,4.736968,85.575000,101.362932,0.639000,0.345700,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."

In [84]:
from sklearn.model_selection import train_test_split
%matplotlib inline
from sklearn.metrics import mean_squared_error, mean_absolute_error, root_mean_squared_error
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

# Split up data into test and train set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=10)

# Set up pipeline for the grid search (for the support vector regression (SVR))
steps = [('scaler', StandardScaler()), ('SVM', SVR())]
pipeline = Pipeline(steps)

# Perform 5-fold cross-validated gridsearch (for the SVR)
grid = GridSearchCV(pipeline, param_grid={'SVM__C': [100], 'SVM__gamma': ['auto'], 'SVM__kernel': ['rbf'],
                                          'SVM__epsilon': [0.001]}, cv=5)

# Fit to the train set and evaluate the model using the test set
grid.fit(X_train, y_train)
svr_score = grid.score(X_train, y_train)
svr_score1 = grid.score(X_test, y_test)
y_predicted = grid.predict(X_test)

ValueError:
All the 5 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
TypeError: float() argument must be a string or a real number, not 'list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\moorh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\moorh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\moorh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\pipeline.py", line 654, in fit
    Xt = self._fit(X, y, routed_params, raw_params=params)
  File "C:\Users\moorh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\pipeline.py", line 588, in _fit
    X, fitted_transformer = fit_transform_one_cached(
                            ~~~~~~~~~~~~~~~~~~~~~~~~^
        cloned_transformer,
        ^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
        params=step_params,
        ^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\moorh\AppData\Local\Programs\Python\Python313\Lib\site-packages\joblib\memory.py", line 312, in __call__
    return self.func(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\moorh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\pipeline.py", line 1551, in _fit_transform_one
    res = transformer.fit_transform(X, y, **params.get("fit_transform", {}))
  File "C:\Users\moorh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "C:\Users\moorh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py", line 921, in fit_transform
    return self.fit(X, y, **fit_params).transform(X)
           ~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\moorh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\moorh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\moorh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_data.py", line 930, in partial_fit
    X = validate_data(
        self,
    ...<4 lines>...
        reset=first_call,
    )
  File "C:\Users\moorh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
  File "C:\Users\moorh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
  File "C:\Users\moorh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
  File "C:\Users\moorh\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\generic.py", line 2153, in __array__
    arr = np.asarray(values, dtype=dtype)
ValueError: setting an array element with a sequence.

In [ ]:
from sklearn.model_selection import train_test_split
%matplotlib inline
from sklearn.metrics import mean_squared_error, mean_absolute_error, root_mean_squared_error
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

# Split up data into test and train set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=10)

# Set up pipeline for the grid search (for the support vector regression (SVR))
steps = [('scaler', StandardScaler()), ('SVM', SVR())]
pipeline = Pipeline(steps)

# Initialize k-fold
inner_cv = KFold(n_splits=5, shuffle=True, random_state=2)
outer_cv = KFold(n_splits=5, shuffle=True, random_state=2)

# Perform 5-fold cross-validated gridsearch (for the SVR)
grid = GridSearchCV(pipeline, param_grid={'SVM__C': [100], 'SVM__gamma': ['auto'], 'SVM__kernel': ['rbf'],
                                          'SVM__epsilon': [0.001]}, cv=inner_cv)
nested_scores = cross_val_score(grid, X, y, cv=outer_cv)

# Fit to the train set and evaluate the model using the test set
grid.fit(X_train, y_train)
svr_score = grid.score(X_train, y_train)
svr_score1 = grid.score(X_test, y_test)
y_predicted = grid.predict(X_test)

In [ ]:
from sklearn.metrics import root_mean_squared_error

# Return cross-validation score
print(nested_scores)
# Return the obtained scores for SVR (including MSE, RMSE and MAE
print('SVR Model: R2 sq on train set: %.4f'% svr_score)
print('SVR Model: R2 sq on test set: %.4f'% svr_score1)
print('SVR Model: MSE on test set: %.4f'% mean_squared_error(y_test, y_predicted))
print('SVR Model: RMSE on test set: %.4f'% root_mean_squared_error(y_test, y_predicted))
print('SVR Model: MAE on test set: %.4f'% mean_absolute_error(y_test, y_predicted))